export interface Product {
  id: string;
  name: string;
  category: string;
  weight: number;       // pounds
  price: number;         // USD (estimated wholesale)
  width: number;         // inches
  height: number;        // inches
  depth: number;         // inches
  color: string;         // hex color for 3D visualization
  emoji: string;
  description: string;
  shelfLife: string;     // e.g. "6 meses"
}

export interface ProductInBox {
  product: Product;
  quantity: number;
  position: { x: number; y: number; z: number };
}

export const PRODUCT_CATEGORIES = [
  'Todos',
  'Granos y Cereales',
  'Lácteos',
  'Aceites y Grasas',
  'Azucares y Endulzantes',
  'Enlatados',
  'Bebidas y Café',
  'Snacks y Galletas',
  'Aseo Personal',
  'Aseo del Hogar',
  'Otros',
] as const;

export const PRODUCTS: Product[] = [
  // ── Granos y Cereales ──
  {
    id: 'arroz-5lb',
    name: 'Arroz 5 lb',
    category: 'Granos y Cereales',
    weight: 5,
    price: 3.50,
    width: 8,
    height: 10,
    depth: 3,
    color: '#F5F5DC',
    emoji: '🍚',
    description: 'Arroz blanco largo, bolsita de 5 libras.',
    shelfLife: '12 meses',
  },
  {
    id: 'frijol-rojo-2lb',
    name: 'Frijol Rojo 2 lb',
    category: 'Granos y Cereales',
    weight: 2,
    price: 2.80,
    width: 7,
    height: 9,
    depth: 2.5,
    color: '#8B0000',
    emoji: '🫘',
    description: 'Frijol rojo para gallo pinto, 2 libras.',
    shelfLife: '12 meses',
  },
  {
    id: 'frijol-negro-2lb',
    name: 'Frijol Negro 2 lb',
    category: 'Granos y Cereales',
    weight: 2,
    price: 2.80,
    width: 7,
    height: 9,
    depth: 2.5,
    color: '#1a1a1a',
    emoji: '🫘',
    description: 'Frijol negro, bolsita de 2 libras.',
    shelfLife: '12 meses',
  },
  {
    id: 'harina-maiz-2lb',
    name: 'Harina de Maíz 2 lb',
    category: 'Granos y Cereales',
    weight: 2,
    price: 1.80,
    width: 7,
    height: 9,
    depth: 2.5,
    color: '#FFD700',
    emoji: '🌽',
    description: 'Harina de maíz para tortillas, 2 libras.',
    shelfLife: '6 meses',
  },
  {
    id: 'harina-trigo-5lb',
    name: 'Harina de Trigo 5 lb',
    category: 'Granos y Cereales',
    weight: 5,
    price: 3.20,
    width: 8,
    height: 10,
    depth: 3,
    color: '#FFF8DC',
    emoji: '🌾',
    description: 'Harina de trigo todo uso, 5 libras.',
    shelfLife: '8 meses',
  },
  {
    id: 'avena-1lb',
    name: 'Avena 1 lb',
    category: 'Granos y Cereales',
    weight: 1,
    price: 1.50,
    width: 5,
    height: 7,
    depth: 2,
    color: '#DEB887',
    emoji: '🥣',
    description: 'Avena en hojuelas, 1 libra.',
    shelfLife: '12 meses',
  },
  {
    id: 'lentejas-1lb',
    name: 'Lentejas 1 lb',
    category: 'Granos y Cereales',
    weight: 1,
    price: 1.60,
    width: 5,
    height: 7,
    depth: 2,
    color: '#8B4513',
    emoji: '🫘',
    description: 'Lentejas enteras, bolsita de 1 libra.',
    shelfLife: '12 meses',
  },
  {
    id: 'garbanzos-1lb',
    name: 'Garbanzos 1 lb',
    category: 'Granos y Cereales',
    weight: 1,
    price: 1.40,
    width: 5,
    height: 7,
    depth: 2,
    color: '#DAA520',
    emoji: '🫘',
    description: 'Garbanzos secos, bolsita de 1 libra.',
    shelfLife: '12 meses',
  },
  {
    id: 'maiz-dulce-2lb',
    name: 'Maíz Dulce 2 lb',
    category: 'Granos y Cereales',
    weight: 2,
    price: 2.20,
    width: 6,
    height: 8,
    depth: 2,
    color: '#FFD700',
    emoji: '🌽',
    description: 'Maíz dulce en grano, 2 libras.',
    shelfLife: '12 meses',
  },
  {
    id: 'pasta-2lb',
    name: 'Pasta Espagueti 2 lb',
    category: 'Granos y Cereales',
    weight: 2,
    price: 1.60,
    width: 3,
    height: 10,
    depth: 3,
    color: '#FFE4B5',
    emoji: '🍝',
    description: 'Espagueti, paquete de 2 libras.',
    shelfLife: '24 meses',
  },

  // ── Lácteos ──
  {
    id: 'leche-polvo-2.2lb',
    name: 'Leche en Polvo 2.2 lb',
    category: 'Lácteos',
    weight: 2.2,
    price: 6.50,
    width: 6,
    height: 8,
    depth: 4,
    color: '#E0E0E0',
    emoji: '🥛',
    description: 'Leche en polvo entera, lata de 2.2 lb.',
    shelfLife: '18 meses',
  },
  {
    id: 'leche-polvo-1lb',
    name: 'Leche en Polvo 1 lb',
    category: 'Lácteos',
    weight: 1,
    price: 3.50,
    width: 4.5,
    height: 6,
    depth: 3,
    color: '#E8E8E8',
    emoji: '🥛',
    description: 'Leche en polvo entera, bolsa de 1 lb.',
    shelfLife: '18 meses',
  },
  {
    id: 'queso-polvo-1lb',
    name: 'Queso en Polvo 1 lb',
    category: 'Lácteos',
    weight: 1,
    price: 4.00,
    width: 5,
    height: 7,
    depth: 2,
    color: '#FFA500',
    emoji: '🧀',
    description: 'Queso parmesano rallado, 1 libra.',
    shelfLife: '12 meses',
  },

  // ── Aceites y Grasas ──
  {
    id: 'aceite-1L',
    name: 'Aceite Vegetal 1L',
    category: 'Aceites y Grasas',
    weight: 2,
    price: 3.80,
    width: 3.5,
    height: 10,
    depth: 3.5,
    color: '#FFD700',
    emoji: '🫒',
    description: 'Aceite vegetal mezcla, botella de 1 litro.',
    shelfLife: '12 meses',
  },
  {
    id: 'margarina-1lb',
    name: 'Margarina 1 lb',
    category: 'Aceites y Grasas',
    weight: 1,
    price: 2.20,
    width: 4,
    height: 3,
    depth: 2,
    color: '#FFFF00',
    emoji: '🧈',
    description: 'Margarina para cocinar, 1 libra.',
    shelfLife: '6 meses',
  },

  // ── Azucares y Endulzantes ──
  {
    id: 'azucar-5lb',
    name: 'Azúcar Blanca 5 lb',
    category: 'Azucares y Endulzantes',
    weight: 5,
    price: 3.00,
    width: 7,
    height: 9,
    depth: 3,
    color: '#FFFFFF',
    emoji: '🍬',
    description: 'Azúcar blanca refinada, bolsita de 5 lb.',
    shelfLife: '24 meses',
  },
  {
    id: 'miel-1lb',
    name: 'Miel de Abeja 1 lb',
    category: 'Azucares y Endulzantes',
    weight: 1,
    price: 5.50,
    width: 4,
    height: 6,
    depth: 2,
    color: '#DAA520',
    emoji: '🍯',
    description: 'Miel de abeja pura, frasco de 1 lb.',
    shelfLife: '24 meses',
  },

  // ── Enlatados ──
  {
    id: 'atun-6pack',
    name: 'Atún en Lata ×6',
    category: 'Enlatados',
    weight: 3,
    price: 7.50,
    width: 8,
    height: 3,
    depth: 5,
    color: '#4169E1',
    emoji: '🐟',
    description: 'Pack de 6 latas de atún en agua.',
    shelfLife: '36 meses',
  },
  {
    id: 'sardinas-3pack',
    name: 'Sardinas en Lata ×3',
    category: 'Enlatados',
    weight: 1.5,
    price: 4.00,
    width: 6,
    height: 3,
    depth: 4,
    color: '#4682B4',
    emoji: '🐟',
    description: 'Pack de 3 latas de sardinas en tomate.',
    shelfLife: '36 meses',
  },
  {
    id: 'frijoles-enlatados-3pack',
    name: 'Frijoles Enlatados ×3',
    category: 'Enlatados',
    weight: 3,
    price: 5.00,
    width: 6,
    height: 5,
    depth: 4,
    color: '#8B4513',
    emoji: '🥫',
    description: 'Pack de 3 latas de frijoles refritos.',
    shelfLife: '24 meses',
  },
  {
    id: 'sopa-sobre-6pack',
    name: 'Sopa en Sobre ×6',
    category: 'Enlatados',
    weight: 1.5,
    price: 3.00,
    width: 8,
    height: 5,
    depth: 2,
    color: '#FF6347',
    emoji: '🍜',
    description: 'Pack de 6 sobres de sopa instantánea.',
    shelfLife: '12 meses',
  },
  {
    id: 'salsa-tomate-3pack',
    name: 'Salsa de Tomate ×3',
    category: 'Enlatados',
    weight: 2,
    price: 3.50,
    width: 6,
    height: 5,
    depth: 4,
    color: '#DC143C',
    emoji: '🍅',
    description: 'Pack de 3 latas de salsa de tomate.',
    shelfLife: '24 meses',
  },
  {
    id: 'chiles-enlatados-2pack',
    name: 'Chiles Jalapeños ×2',
    category: 'Enlatados',
    weight: 1,
    price: 2.50,
    width: 4,
    height: 4,
    depth: 3,
    color: '#228B22',
    emoji: '🌶️',
    description: 'Pack de 2 frascos de chiles jalapeños.',
    shelfLife: '24 meses',
  },
  {
    id: 'maiz-enlatado-3pack',
    name: 'Maíz Enlatado ×3',
    category: 'Enlatados',
    weight: 2,
    price: 3.00,
    width: 6,
    height: 5,
    depth: 4,
    color: '#FFD700',
    emoji: '🌽',
    description: 'Pack de 3 latas de maíz dulce.',
    shelfLife: '24 meses',
  },

  // ── Bebidas y Café ──
  {
    id: 'cafe-molido-1lb',
    name: 'Café Molido 1 lb',
    category: 'Bebidas y Café',
    weight: 1,
    price: 5.00,
    width: 5,
    height: 7,
    depth: 2.5,
    color: '#3E2723',
    emoji: '☕',
    description: 'Café molido tostado, bolsita de 1 lb.',
    shelfLife: '12 meses',
  },
  {
    id: 'cafe-instantaneo-7oz',
    name: 'Café Instantáneo 7 oz',
    category: 'Bebidas y Café',
    weight: 0.44,
    price: 6.00,
    width: 3,
    height: 5,
    depth: 2,
    color: '#4E342E',
    emoji: '☕',
    description: 'Café instantáneo, frasco de 7 oz.',
    shelfLife: '24 meses',
  },
  {
    id: 'cacao-1lb',
    name: 'Cacao en Polvo 1 lb',
    category: 'Bebidas y Café',
    weight: 1,
    price: 4.50,
    width: 5,
    height: 7,
    depth: 2,
    color: '#5D4037',
    emoji: '🍫',
    description: 'Cacao en polvo para bebida, 1 libra.',
    shelfLife: '12 meses',
  },
  {
    id: 'te-24sobres',
    name: 'Té en Sobre ×24',
    category: 'Bebidas y Café',
    weight: 0.3,
    price: 2.50,
    width: 3,
    height: 4,
    depth: 2.5,
    color: '#81C784',
    emoji: '🫖',
    description: 'Caja de 24 sobres de té variado.',
    shelfLife: '24 meses',
  },

  // ── Snacks y Galletas ──
  {
    id: 'galletas-1lb',
    name: 'Galletas Saladas 1 lb',
    category: 'Snacks y Galletas',
    weight: 1,
    price: 2.00,
    width: 8,
    height: 8,
    depth: 2,
    color: '#DEB887',
    emoji: '🍪',
    description: 'Galletas saladas tipo crackers, 1 libra.',
    shelfLife: '6 meses',
  },
  {
    id: 'avena-cookies-1lb',
    name: 'Galletas de Avena 1 lb',
    category: 'Snacks y Galletas',
    weight: 1,
    price: 2.50,
    width: 8,
    height: 8,
    depth: 2,
    color: '#D2B48C',
    emoji: '🍪',
    description: 'Galletas de avena con pasas, 1 libra.',
    shelfLife: '6 meses',
  },
  {
    id: 'cereal-1lb',
    name: 'Cereal de Maíz 1 lb',
    category: 'Snacks y Galletas',
    weight: 1,
    price: 3.00,
    width: 8,
    height: 10,
    depth: 2.5,
    color: '#FFA726',
    emoji: '🥣',
    description: 'Cereal de maíz tostado, 1 libra.',
    shelfLife: '6 meses',
  },

  // ── Aseo Personal ──
  {
    id: 'jabon-3pack',
    name: 'Jabón de Tocador ×3',
    category: 'Aseo Personal',
    weight: 0.75,
    price: 2.50,
    width: 6,
    height: 3,
    depth: 2,
    color: '#FFC0CB',
    emoji: '🧼',
    description: 'Pack de 3 jabones de tocador.',
    shelfLife: '24 meses',
  },
  {
    id: 'pasta-dental-1',
    name: 'Pasta Dental',
    category: 'Aseo Personal',
    weight: 0.4,
    price: 2.00,
    width: 2,
    height: 5,
    depth: 1.5,
    color: '#87CEEB',
    emoji: '🪥',
    description: 'Pasta dental de 6.4 oz.',
    shelfLife: '24 meses',
  },
  {
    id: 'champu-1',
    name: 'Champú 12 oz',
    category: 'Aseo Personal',
    weight: 0.75,
    price: 3.50,
    width: 2.5,
    height: 7,
    depth: 2.5,
    color: '#9370DB',
    emoji: '🧴',
    description: 'Champú anticaspa, botella de 12 oz.',
    shelfLife: '24 meses',
  },
  {
    id: 'desodorante-1',
    name: 'Desodorante Roll-On',
    category: 'Aseo Personal',
    weight: 0.3,
    price: 2.80,
    width: 2,
    height: 5,
    depth: 2,
    color: '#708090',
    emoji: '🧴',
    description: 'Desodorante roll-on para hombre/dama.',
    shelfLife: '24 meses',
  },

  // ── Aseo del Hogar ──
  {
    id: 'detergente-2lb',
    name: 'Detergente en Polvo 2 lb',
    category: 'Aseo del Hogar',
    weight: 2,
    price: 3.50,
    width: 7,
    height: 9,
    depth: 3,
    color: '#00CED1',
    emoji: '🧹',
    description: 'Detergente en polvo para ropa, 2 lb.',
    shelfLife: '24 meses',
  },
  {
    id: 'jabon-trapo-1',
    name: 'Jabón de Trapo 1 lb',
    category: 'Aseo del Hogar',
    weight: 1,
    price: 1.50,
    width: 6,
    height: 3,
    depth: 2,
    color: '#20B2AA',
    emoji: '🧽',
    description: 'Jabón de trapo multiusos, 1 libra.',
    shelfLife: '24 meses',
  },
  {
    id: 'cloro-1gal',
    name: 'Cloro 1 galón',
    category: 'Aseo del Hogar',
    weight: 8.3,
    price: 3.00,
    width: 6,
    height: 11,
    depth: 6,
    color: '#E0FFFF',
    emoji: '🧴',
    description: 'Cloro líquido blanqueador, 1 galón.',
    shelfLife: '12 meses',
  },
  {
    id: 'papel-higienico-4',
    name: 'Papel Higiénico ×4',
    category: 'Aseo del Hogar',
    weight: 2,
    price: 4.00,
    width: 10,
    height: 4,
    depth: 8,
    color: '#F5F5F5',
    emoji: '🧻',
    description: 'Pack de 4 rollos de papel higiénico.',
    shelfLife: '24 meses',
  },

  // ── Otros ──
  {
    id: 'sal-1lb',
    name: 'Sal 1 lb',
    category: 'Otros',
    weight: 1,
    price: 0.80,
    width: 4,
    height: 6,
    depth: 1.5,
    color: '#F0F0F0',
    emoji: '🧂',
    description: 'Sal de mesa yodada, 1 libra.',
    shelfLife: '24 meses',
  },
  {
    id: 'vinagre-1L',
    name: 'Vinagre Blanco 1L',
    category: 'Otros',
    weight: 2.2,
    price: 1.80,
    width: 3.5,
    height: 10,
    depth: 3.5,
    color: '#FAFAD2',
    emoji: '🫗',
    description: 'Vinagre blanco destilado, 1 litro.',
    shelfLife: '24 meses',
  },
  {
    id: 'comino-0.5lb',
    name: 'Comino 0.5 lb',
    category: 'Otros',
    weight: 0.5,
    price: 1.50,
    width: 3,
    height: 5,
    depth: 1.5,
    color: '#B8860B',
    emoji: '✨',
    description: 'Comino molido, 0.5 libras.',
    shelfLife: '12 meses',
  },
  {
    id: 'achiote-0.5lb',
    name: 'Achiote 0.5 lb',
    category: 'Otros',
    weight: 0.5,
    price: 1.80,
    width: 3,
    height: 5,
    depth: 1.5,
    color: '#FF4500',
    emoji: '🌶️',
    description: 'Pasta de achiote, 0.5 libras.',
    shelfLife: '12 meses',
  },
  {
    id: 'bizcocho-polvo-1lb',
    name: 'Bizcocho en Polvo 1 lb',
    category: 'Otros',
    weight: 1,
    price: 2.00,
    width: 6,
    height: 8,
    depth: 2,
    color: '#FFE4E1',
    emoji: '🎂',
    description: 'Mezcla para bizcocho, 1 libra.',
    shelfLife: '12 meses',
  },
  {
    id: 'gelatina-6pack',
    name: 'Gelatina ×6 sobres',
    category: 'Otros',
    weight: 0.6,
    price: 2.00,
    width: 7,
    height: 4,
    depth: 1.5,
    color: '#FF69B4',
    emoji: '🍮',
    description: 'Pack de 6 sobres de gelatina variada.',
    shelfLife: '12 meses',
  },
  {
    id: 'margarina-3lb',
    name: 'Margarina 3 lb',
    category: 'Aceites y Grasas',
    weight: 3,
    price: 5.50,
    width: 6,
    height: 4,
    depth: 3,
    color: '#FFEB3B',
    emoji: '🧈',
    description: 'Margarina para cocinar, balde de 3 lb.',
    shelfLife: '6 meses',
  },
  {
    id: 'manteca-cerdo-1lb',
    name: 'Manteca de Cerdo 1 lb',
    category: 'Aceites y Grasas',
    weight: 1,
    price: 2.00,
    width: 5,
    height: 3,
    depth: 2,
    color: '#FFF9C4',
    emoji: '🥓',
    description: 'Manteca de cerdo en bloque, 1 libra.',
    shelfLife: '6 meses',
  },
];
