export type PackagingType = 'bag' | 'can' | 'box' | 'bottle' | 'jar' | 'bar' | 'pouch';

export interface Product {
  id: string;
  name: string;
  nameEs: string;
  category: string;
  weight: number;        // pounds (libras)
  price: number;          // USD - Walmart price
  width: number;          // inches (pulgadas)
  height: number;         // inches
  depth: number;          // inches
  volume: number;         // cubic inches (W × H × D)
  color: string;          // hex color for 3D visualization
  emoji: string;
  shelfLife: string;      // shelf life
  walmartUrl: string;     // product URL
  description: string;    // Spanish description
  packagingType: PackagingType;
}

export interface ProductInBox {
  product: Product;
  quantity: number;
  position: { x: number; y: number; z: number };
}

export const PRODUCT_CATEGORIES = [
  'Todos',
  'Granos y Cereales',
  'Lácteos Estables',
  'Aceites y Grasas',
  'Azucares y Endulzantes',
  'Enlatados',
  'Bebidas y Café',
  'Snacks y Desayuno',
  'Chocolates y Dulces',
  'Semillas y Frutos Secos',
  'Condimentos y Salsas',
  'Aseo Personal',
  'Aseo del Hogar',
] as const;

// ─────────────────────────────────────────────────────────────────────────────
// PRODUCTS FROM WALMART.COM — Great Value & name brands
// Prices as of 2025, dimensions estimated from standard packaging
// Sales tax varies by state (avg 6.5-8%) — applied at checkout
// ─────────────────────────────────────────────────────────────────────────────
export const PRODUCTS: Product[] = [

  // ═══════════ GRANOS Y CEREALES ═══════════
  {
    id: 'gv-rice-5lb',
    name: 'Great Value Long Grain White Rice, 5 lb',
    nameEs: 'Arroz Blanco Grano Largo 5 lb',
    category: 'Granos y Cereales',
    weight: 5,
    price: 3.78,
    width: 7.5,
    height: 10,
    depth: 2.5,
    volume: 187.5,
    color: '#F5F5DC',
    emoji: '🍚',
    shelfLife: '12 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-long-grain-white-rice-5-lb/10314157',
    description: 'Arroz blanco grano largo Great Value, bolsa de 5 libras.',
    packagingType: 'bag',
  },
  {
    id: 'gv-pinto-beans-2lb',
    name: 'Great Value Dried Pinto Beans, 2 lb',
    nameEs: 'Frijoles Pintos Secos 2 lb',
    category: 'Granos y Cereales',
    weight: 2,
    price: 2.62,
    width: 7,
    height: 9,
    depth: 2.5,
    volume: 157.5,
    color: '#8B6914',
    emoji: '🫘',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-dried-pinto-beans-2-lb/155982624',
    description: 'Frijoles pintos secos Great Value, bolsa de 2 libras.',
    packagingType: 'bag',
  },
  {
    id: 'gv-black-beans-15oz',
    name: 'Great Value Black Beans, 15.5 oz Can, 4 Pack',
    nameEs: 'Frijoles Negros Enlatados ×4',
    category: 'Granos y Cereales',
    weight: 3.9,
    price: 3.48,
    width: 10,
    height: 4.5,
    depth: 6,
    volume: 270,
    color: '#1a1a1a',
    emoji: '🫘',
    shelfLife: '36 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-black-beans-15-5-oz-cans-4-count/456294568',
    description: 'Pack de 4 latas de frijoles negros, 15.5 oz cada una.',
    packagingType: 'can',
  },
  {
    id: 'gv-flour-5lb',
    name: 'Great Value All-Purpose Flour, 5 lb',
    nameEs: 'Harina de Trigo Todo Uso 5 lb',
    category: 'Granos y Cereales',
    weight: 5,
    price: 3.48,
    width: 7.5,
    height: 10,
    depth: 2.5,
    volume: 187.5,
    color: '#FFF8DC',
    emoji: '🌾',
    shelfLife: '12 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-all-purpose-flour-5-lb/10450619',
    description: 'Harina de trigo todo uso Great Value, 5 libras.',
    packagingType: 'bag',
  },
  {
    id: 'gv-cornmeal-2lb',
    name: 'Great Value Yellow Cornmeal, 2 lb',
    nameEs: 'Harina de Maíz Amarilla 2 lb',
    category: 'Granos y Cereales',
    weight: 2,
    price: 1.76,
    width: 7,
    height: 8.5,
    depth: 2.5,
    volume: 148.75,
    color: '#FFD700',
    emoji: '🌽',
    shelfLife: '12 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-yellow-cornmeal-2-lb/10450613',
    description: 'Harina de maíz amarilla Great Value, 2 libras.',
    packagingType: 'bag',
  },
  {
    id: 'gv-spaghetti-16oz',
    name: 'Great Value Spaghetti, 16 oz',
    nameEs: 'Espagueti 16 oz',
    category: 'Granos y Cereales',
    weight: 1,
    price: 1.18,
    width: 3,
    height: 10,
    depth: 2.5,
    volume: 75,
    color: '#FFE4B5',
    emoji: '🍝',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-spaghetti-16-oz/10450637',
    description: 'Espagueti Great Value, paquete de 16 oz.',
    packagingType: 'bag',
  },
  {
    id: 'gv-mac-cheese-5pk',
    name: 'Great Value Macaroni and Cheese, 7.25 oz, 5 Pack',
    nameEs: 'Macarrones con Queso ×5',
    category: 'Granos y Cereales',
    weight: 2.3,
    price: 3.98,
    width: 9,
    height: 6,
    depth: 4.5,
    volume: 243,
    color: '#FFA500',
    emoji: '🧀',
    shelfLife: '18 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-mac-and-cheese-7-25-oz-5-count/470844108',
    description: 'Pack de 5 macarrones con queso Great Value, 7.25 oz c/u.',
    packagingType: 'box',
  },
  {
    id: 'gv-oatmeal-42oz',
    name: 'Great Value Old Fashioned Oats, 42 oz',
    nameEs: 'Avena en Hojuelas 42 oz',
    category: 'Granos y Cereales',
    weight: 2.6,
    price: 3.28,
    width: 8,
    height: 10,
    depth: 3,
    volume: 240,
    color: '#DEB887',
    emoji: '🥣',
    shelfLife: '12 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-old-fashioned-oats-42-oz/10450641',
    description: 'Avena en hojuelas Great Value, 42 oz.',
    packagingType: 'bag',
  },
  {
    id: 'gv-lentils-1lb',
    name: 'Great Value Dried Lentils, 16 oz',
    nameEs: 'Lentejas Secas 16 oz',
    category: 'Granos y Cereales',
    weight: 1,
    price: 1.48,
    width: 5,
    height: 7,
    depth: 2,
    volume: 70,
    color: '#8B4513',
    emoji: '🫘',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-dried-lentils-16-oz/456920738',
    description: 'Lentejas secas Great Value, 16 oz.',
    packagingType: 'bag',
  },
  {
    id: 'gv-garbanzos-1lb',
    name: 'Great Value Dried Chickpeas, 16 oz',
    nameEs: 'Garbanzos Secos 16 oz',
    category: 'Granos y Cereales',
    weight: 1,
    price: 1.28,
    width: 5,
    height: 7,
    depth: 2,
    volume: 70,
    color: '#DAA520',
    emoji: '🫘',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-dried-chickpeas-16-oz/456920736',
    description: 'Garbanzos secos Great Value, 16 oz.',
    packagingType: 'bag',
  },

  // ═══════════ LÁCTEOS Y QUESO ═══════════
  {
    id: 'gv-milk-powder-25oz',
    name: 'Great Value Non-Fat Dry Milk, 25.6 oz',
    nameEs: 'Leche en Polvo Descremada 25.6 oz',
    category: 'Lácteos Estables',
    weight: 1.6,
    price: 6.98,
    width: 5.5,
    height: 7.5,
    depth: 3.5,
    volume: 144.38,
    color: '#E0E0E0',
    emoji: '🥛',
    shelfLife: '18 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-non-fat-dry-milk-25-6-oz/10450602',
    description: 'Leche en polvo descremada Great Value, 25.6 oz.',
    packagingType: 'bag',
  },
  {
    id: 'gv-nido-12oz',
    name: 'Nestle NIDO Dry Whole Milk, 12.6 oz',
    nameEs: 'Leche en Polvo Entera NIDO 12.6 oz',
    category: 'Lácteos Estables',
    weight: 0.79,
    price: 5.48,
    width: 4.5,
    height: 6.5,
    depth: 3,
    volume: 87.75,
    color: '#F5DEB3',
    emoji: '🥛',
    shelfLife: '18 meses',
    walmartUrl: 'https://www.walmart.com/ip/nestle-nido-kinder-1-12-6-oz/10312650',
    description: 'Leche en polvo entera NIDO, 12.6 oz.',
    packagingType: 'can',
  },


  // ═══════════ ACEITES Y GRASAS ═══════════
  {
    id: 'gv-vegetable-oil-48oz',
    name: 'Great Value Vegetable Oil, 48 fl oz',
    nameEs: 'Aceite Vegetal 48 fl oz',
    category: 'Aceites y Grasas',
    weight: 3,
    price: 3.48,
    width: 3.5,
    height: 10.5,
    depth: 3.5,
    volume: 128.63,
    color: '#FFD700',
    emoji: '🫒',
    shelfLife: '18 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-100-pure-vegetable-oil-48-fl-oz/10450596',
    description: 'Aceite vegetal 100% puro Great Value, 48 fl oz.',
    packagingType: 'bottle',
  },

  {
    id: 'gv-peanut-butter-40oz',
    name: 'Great Value Creamy Peanut Butter, 40 oz',
    nameEs: 'Mantequilla de Cacahuete 40 oz',
    category: 'Aceites y Grasas',
    weight: 2.5,
    price: 4.98,
    width: 4.5,
    height: 6,
    depth: 4.5,
    volume: 121.5,
    color: '#D2691E',
    emoji: '🥜',
    shelfLife: '6 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-creamy-peanut-butter-40-oz/10450610',
    description: 'Mantequilla de cacahuete cremosa Great Value, 40 oz.',
    packagingType: 'jar',
  },

  // ═══════════ AZUCARES Y ENDULZANTES ═══════════
  {
    id: 'gv-sugar-4lb',
    name: 'Great Value Granulated Sugar, 4 lb',
    nameEs: 'Azúcar Blanca 4 lb',
    category: 'Azucares y Endulzantes',
    weight: 4,
    price: 3.28,
    width: 6.5,
    height: 8.5,
    depth: 2.5,
    volume: 138.13,
    color: '#FFFFFF',
    emoji: '🍬',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-granulated-sugar-4-lb/10450607',
    description: 'Azúcar blanca granulada Great Value, 4 libras.',
    packagingType: 'bag',
  },
  {
    id: 'gv-honey-12oz',
    name: 'Great Value Clover Honey, 12 oz',
    nameEs: 'Miel de Trébol 12 oz',
    category: 'Azucares y Endulzantes',
    weight: 0.75,
    price: 4.48,
    width: 3.5,
    height: 5.5,
    depth: 2.5,
    volume: 48.13,
    color: '#DAA520',
    emoji: '🍯',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-clover-honey-12-oz/10450609',
    description: 'Miel de trébol pura Great Value, 12 oz.',
    packagingType: 'jar',
  },
  {
    id: 'gv-syrup-24oz',
    name: 'Great Value Original Syrup, 24 oz',
    nameEs: 'Jarabe de Arce 24 oz',
    category: 'Azucares y Endulzantes',
    weight: 1.5,
    price: 2.48,
    width: 3,
    height: 8,
    depth: 3,
    volume: 72,
    color: '#8B4513',
    emoji: '🥞',
    shelfLife: '12 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-original-syrup-24-oz/10450611',
    description: 'Jarabe original Great Value, 24 oz.',
    packagingType: 'bottle',
  },

  // ═══════════ ENLATADOS ═══════════
  {
    id: 'gv-tuna-6pk',
    name: 'Great Value Chunk Light Tuna in Water, 5 oz, 6 Pack',
    nameEs: 'Atún en Agua ×6 latas',
    category: 'Enlatados',
    weight: 1.9,
    price: 6.98,
    width: 9,
    height: 4,
    depth: 5.5,
    volume: 198,
    color: '#4169E1',
    emoji: '🐟',
    shelfLife: '36 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-chunk-light-tuna-in-water-5-oz-cans-6-count/10450590',
    description: 'Pack de 6 latas de atún en agua Great Value, 5 oz c/u.',
    packagingType: 'can',
  },
  {
    id: 'gv-chicken-broth-4pk',
    name: 'Great Value Chicken Broth, 14.5 oz, 4 Pack',
    nameEs: 'Caldo de Pollo ×4 latas',
    category: 'Enlatados',
    weight: 3.6,
    price: 2.98,
    width: 9,
    height: 4,
    depth: 5.5,
    volume: 198,
    color: '#DAA520',
    emoji: '🥣',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-chicken-broth-14-5-oz-cans-4-count/10450593',
    description: 'Pack de 4 latas de caldo de pollo Great Value, 14.5 oz c/u.',
    packagingType: 'can',
  },
  {
    id: 'gv-tomato-sauce-3pk',
    name: 'Great Value Tomato Sauce, 15 oz, 3 Pack',
    nameEs: 'Salsa de Tomate ×3 latas',
    category: 'Enlatados',
    weight: 2.8,
    price: 2.18,
    width: 7,
    height: 5,
    depth: 3.5,
    volume: 122.5,
    color: '#DC143C',
    emoji: '🍅',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-tomato-sauce-15-oz-cans-3-count/10450595',
    description: 'Pack de 3 latas de salsa de tomate Great Value, 15 oz c/u.',
    packagingType: 'can',
  },
  {
    id: 'gv-corn-3pk',
    name: 'Great Value Whole Kernel Sweet Corn, 15.25 oz, 3 Pack',
    nameEs: 'Maíz Dulce Entero ×3 latas',
    category: 'Enlatados',
    weight: 2.9,
    price: 2.28,
    width: 7,
    height: 5,
    depth: 3.5,
    volume: 122.5,
    color: '#FFD700',
    emoji: '🌽',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-whole-kernel-sweet-corn-15-25-oz-cans-3-count/10450589',
    description: 'Pack de 3 latas de maíz dulce Great Value, 15.25 oz c/u.',
    packagingType: 'can',
  },
  {
    id: 'gv-tomato-paste-4pk',
    name: 'Great Value Tomato Paste, 6 oz, 4 Pack',
    nameEs: 'Pasta de Tomate ×4 latas',
    category: 'Enlatados',
    weight: 1.5,
    price: 1.98,
    width: 7,
    height: 3,
    depth: 3,
    volume: 63,
    color: '#B22222',
    emoji: '🍅',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-tomato-paste-6-oz-cans-4-count/10450586',
    description: 'Pack de 4 latas de pasta de tomate Great Value, 6 oz c/u.',
    packagingType: 'can',
  },
  {
    id: 'gv-refried-beans-3pk',
    name: 'Great Value Refried Beans, 16 oz, 3 Pack',
    nameEs: 'Frijoles Refritos ×3 latas',
    category: 'Enlatados',
    weight: 3,
    price: 3.28,
    width: 9,
    height: 5,
    depth: 4,
    volume: 180,
    color: '#8B4513',
    emoji: '🥫',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-refried-beans-16-oz-cans-3-count/10450585',
    description: 'Pack de 3 latas de frijoles refritos Great Value, 16 oz c/u.',
    packagingType: 'can',
  },
  {
    id: 'gv-jalapenos-2pk',
    name: 'La Costena Sliced Jalapenos, 12 oz, 2 Pack',
    nameEs: 'Chiles Jalapeños ×2 frascos',
    category: 'Enlatados',
    weight: 1.5,
    price: 3.48,
    width: 4,
    height: 5,
    depth: 3,
    volume: 60,
    color: '#228B22',
    emoji: '🌶️',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/la-costena-sliced-jalapenos-12-oz-jar-2-count/20814033',
    description: 'Pack de 2 frascos de chiles jalapeños rebanados La Costena.',
    packagingType: 'jar',
  },

  // ═══════════ BEBIDAS Y CAFÉ ═══════════
  {
    id: 'gv-coffee-packet-7oz',
    name: 'Great Value Ground Coffee, Classic Roast, 7 oz',
    nameEs: 'Café Molido Tueste Clásico 7 oz',
    category: 'Bebidas y Café',
    weight: 0.44,
    price: 3.28,
    width: 3,
    height: 5.5,
    depth: 1.5,
    volume: 24.75,
    color: '#3E2723',
    emoji: '☕',
    shelfLife: '12 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-ground-coffee-classic-roast-7-oz/10450603',
    description: 'Paquetito de café molido Great Value, 7 oz.',
    packagingType: 'pouch',
  },
  {
    id: 'gv-coffee-packet-30oz',
    name: 'Great Value Ground Coffee, Classic Roast, 30.5 oz',
    nameEs: 'Café Molido Tueste Clásico 30.5 oz',
    category: 'Bebidas y Café',
    weight: 1.9,
    price: 5.98,
    width: 5,
    height: 8,
    depth: 2.5,
    volume: 100,
    color: '#5D4037',
    emoji: '☕',
    shelfLife: '12 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-ground-coffee-classic-roast-30-5-oz/10450603',
    description: 'Bolsa de café molido Great Value, 30.5 oz.',
    packagingType: 'bag',
  },
  {
    id: 'gv-instant-coffee-sachet-3pk',
    name: 'Great Value Instant Coffee, 3 Sachets',
    nameEs: 'Café Instantáneo ×3 sobres',
    category: 'Bebidas y Café',
    weight: 0.19,
    price: 1.98,
    width: 4,
    height: 3,
    depth: 0.3,
    volume: 3.6,
    color: '#4E342E',
    emoji: '☕',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-instant-coffee-7-oz/10450604',
    description: '3 sobres individuales de café instantáneo.',
    packagingType: 'pouch',
  },
  {
    id: 'fv-coffee-cream-15oz',
    name: 'Great Value Coffee Creamer, French Vanilla, 15 oz',
    nameEs: 'Crema para Café Vainilla 15 oz',
    category: 'Bebidas y Café',
    weight: 0.94,
    price: 3.48,
    width: 3,
    height: 7,
    depth: 3,
    volume: 63,
    color: '#FFF8DC',
    emoji: '☕',
    shelfLife: '9 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-creamer-french-vanilla-15-oz/10450605',
    description: 'Crema para café sabor vainilla Great Value, 15 oz.',
    packagingType: 'bottle',
  },
  {
    id: 'gv-cappuccino-6pk',
    name: 'Great Value French Vanilla Cappuccino, 6 Pack',
    nameEs: 'Capuchino Vainilla ×6 sobres',
    category: 'Bebidas y Café',
    weight: 0.53,
    price: 3.48,
    width: 7,
    height: 4,
    depth: 2,
    volume: 56,
    color: '#D2B48C',
    emoji: '☕',
    shelfLife: '18 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-french-vanilla-cappuccino/10450607',
    description: '6 sobres de capuchino vainilla instantáneo.',
    packagingType: 'box',
  },
  {
    id: 'gv-cocoa-10oz',
    name: 'Great Value Rich Chocolate Cocoa, 10 oz',
    nameEs: 'Cacao en Polvo Chocolate 10 oz',
    category: 'Bebidas y Café',
    weight: 0.63,
    price: 2.48,
    width: 4,
    height: 6,
    depth: 2,
    volume: 48,
    color: '#5D4037',
    emoji: '🍫',
    shelfLife: '12 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-rich-chocolate-cocoa-10-oz/10450606',
    description: 'Cacao en polvo chocolate Great Value, 10 oz.',
    packagingType: 'bag',
  },
  // ── Café La Llave ──
  {
    id: 'la-llave-brick-10oz',
    name: 'Cafe La Llave Espresso, Dark Roast, 10 oz Brick',
    nameEs: 'Cafe La Llave Espresso Tueste Oscuro 10 oz Ladrillo',
    category: 'Bebidas y Café',
    weight: 0.63,
    price: 4.98,
    width: 5,
    height: 7,
    depth: 2,
    volume: 70,
    color: '#1B5E20',
    emoji: '☕',
    shelfLife: '18 meses',
    walmartUrl: 'https://www.walmart.com/ip/cafe-la-llave-dark-roast-espresso-coffee-10-oz/10454135',
    description: 'Cafe La Llave espresso tueste oscuro, presentacion ladrillo de 10 oz. El sabor autentico cubano.',
    packagingType: 'bag',
  },
  {
    id: 'la-llave-can-10oz',
    name: 'Cafe La Llave Cuban Style Espresso, 10 oz Can',
    nameEs: 'Cafe La Llave Estilo Cubano 10 oz Lata',
    category: 'Bebidas y Café',
    weight: 0.63,
    price: 5.48,
    width: 4,
    height: 6,
    depth: 4,
    volume: 96,
    color: '#2E7D32',
    emoji: '☕',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/cafe-la-llave-cuban-style-espresso-10-oz/15800728',
    description: 'Cafe La Llave estilo cubano en lata metalica de 10 oz. Sabor intenso y cremoso.',
    packagingType: 'can',
  },
  {
    id: 'la-llave-can-36oz',
    name: 'Cafe La Llave Espresso, Dark Roast, 36 oz Can',
    nameEs: 'Cafe La Llave Espresso Tueste Oscuro 36 oz Lata',
    category: 'Bebidas y Café',
    weight: 2.25,
    price: 12.98,
    width: 5.5,
    height: 8,
    depth: 5.5,
    volume: 242,
    color: '#1B5E20',
    emoji: '☕',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/cafe-la-llave-dark-roast-espresso-coffee-36-oz/456114537',
    description: 'Cafe La Llave espresso lata grande de 36 oz. Ideal para familias que aman el cafe cubano.',
    packagingType: 'can',
  },
  // ── Café Bustelo ──
  {
    id: 'bustelo-brick-10oz',
    name: 'Cafe Bustelo Espresso Style Dark Roast, 10 oz Brick',
    nameEs: 'Cafe Bustelo Estilo Espresso Tueste Oscuro 10 oz Ladrillo',
    category: 'Bebidas y Café',
    weight: 0.63,
    price: 4.48,
    width: 5,
    height: 7,
    depth: 2,
    volume: 70,
    color: '#F9A825',
    emoji: '☕',
    shelfLife: '18 meses',
    walmartUrl: 'https://www.walmart.com/ip/cafe-bustelo-cafe-espresso-style-dark-roast-ground-coffee-10-oz/10454167',
    description: 'Cafe Bustelo estilo espresso tueste oscuro, ladrillo de 10 oz. Cafe latino autentico.',
    packagingType: 'bag',
  },
  {
    id: 'bustelo-can-10oz',
    name: 'Cafe Bustelo Espresso Style Dark Roast, 10 oz Can',
    nameEs: 'Cafe Bustelo Estilo Espresso 10 oz Lata',
    category: 'Bebidas y Café',
    weight: 0.63,
    price: 4.98,
    width: 4,
    height: 6,
    depth: 4,
    volume: 96,
    color: '#FBC02D',
    emoji: '☕',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/cafe-bustelo-cafe-espresso-style-dark-roast-ground-coffee-10-oz-can/15800745',
    description: 'Cafe Bustelo estilo espresso en lata metalica de 10 oz. Sabor fuerte y aromatico.',
    packagingType: 'can',
  },
  {
    id: 'bustelo-can-12oz',
    name: 'Cafe Bustelo Espresso Style Dark Roast, 12 oz Can',
    nameEs: 'Cafe Bustelo Estilo Espresso 12 oz Lata',
    category: 'Bebidas y Café',
    weight: 0.75,
    price: 5.48,
    width: 4,
    height: 6.5,
    depth: 4,
    volume: 104,
    color: '#F9A825',
    emoji: '☕',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/cafe-bustelo-cafe-espresso-style-dark-roast-ground-coffee-12-oz/456114526',
    description: 'Cafe Bustelo estilo espresso lata de 12 oz. El clasico cafe latinoamericano.',
    packagingType: 'can',
  },
  {
    id: 'bustelo-brick-24oz',
    name: 'Cafe Bustelo Espresso Style Dark Roast, 24 oz Brick',
    nameEs: 'Cafe Bustelo Estilo Espresso 24 oz Ladrillo',
    category: 'Bebidas y Café',
    weight: 1.5,
    price: 7.98,
    width: 6,
    height: 9,
    depth: 2.5,
    volume: 135,
    color: '#FBC02D',
    emoji: '☕',
    shelfLife: '18 meses',
    walmartUrl: 'https://www.walmart.com/ip/cafe-bustelo-cafe-espresso-style-dark-roast-ground-coffee-24-oz/456114530',
    description: 'Cafe Bustelo espresso ladrillo grande de 24 oz. Para los que no pueden vivir sin su cafe.',
    packagingType: 'bag',
  },

  // ═══════════ SNACKS Y DESAYUNO ═══════════
  {
    id: 'gv-corn-flakes-13oz',
    name: 'Great Value Corn Flakes Cereal, 13 oz',
    nameEs: 'Cereal Hojuelas de Maíz 13 oz',
    category: 'Snacks y Desayuno',
    weight: 0.81,
    price: 1.98,
    width: 8,
    height: 10,
    depth: 2.5,
    volume: 200,
    color: '#FFA726',
    emoji: '🥣',
    shelfLife: '9 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-corn-flakes-cereal-13-oz/10450618',
    description: 'Cereal hojuelas de maíz Great Value, 13 oz.',
    packagingType: 'box',
  },
  {
    id: 'gv-pancake-mix-32oz',
    name: 'Great Value Buttermilk Pancake Mix, 32 oz',
    nameEs: 'Mezcla para Panqueques 32 oz',
    category: 'Snacks y Desayuno',
    weight: 2,
    price: 2.28,
    width: 5,
    height: 8,
    depth: 2.5,
    volume: 100,
    color: '#FFE4B5',
    emoji: '🥞',
    shelfLife: '9 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-buttermilk-pancake-complete-mix-32-oz/10450615',
    description: 'Mezcla para panqueques Great Value, 32 oz.',
    packagingType: 'bag',
  },
  {
    id: 'gv-granola-20oz',
    name: 'Great Value Granola, Honey & Oats, 20 oz',
    nameEs: 'Granola Miel y Avena 20 oz',
    category: 'Snacks y Desayuno',
    weight: 1.25,
    price: 2.98,
    width: 7,
    height: 9,
    depth: 2.5,
    volume: 157.5,
    color: '#D2B48C',
    emoji: '🥣',
    shelfLife: '6 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-granola-honey-oats-20-oz/470848029',
    description: 'Granola miel y avena Great Value, 20 oz.',
    packagingType: 'bag',
  },
  {
    id: 'gv-crackers-1lb',
    name: 'Great Value Saltine Crackers, 16 oz',
    nameEs: 'Galletas Saladas 16 oz',
    category: 'Snacks y Desayuno',
    weight: 1,
    price: 1.48,
    width: 9,
    height: 6,
    depth: 4,
    volume: 216,
    color: '#DEB887',
    emoji: '🍪',
    shelfLife: '9 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-original-saltine-crackers-16-oz/10450619',
    description: 'Galletas saladas Great Value, 16 oz.',
    packagingType: 'box',
  },

  // ═══════════ ASEO PERSONAL ═══════════
  {
    id: 'gv-soap-3pk',
    name: 'Dial Bar Soap, Gold, 4 oz, 3 Pack',
    nameEs: 'Jabón de Tocador ×3 barras',
    category: 'Aseo Personal',
    weight: 0.75,
    price: 3.48,
    width: 6,
    height: 3,
    depth: 2,
    volume: 36,
    color: '#FFC0CB',
    emoji: '🧼',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/dial-gold-antibacterial-deodorant-bar-soap-4-oz-3-count/10313825',
    description: 'Pack de 3 barras de jabón Dial antibacterial, 4 oz c/u.',
    packagingType: 'bar',
  },
  {
    id: 'gv-toothpaste-1',
    name: 'Colgate Cavity Protection Toothpaste, 6 oz',
    nameEs: 'Pasta Dental Colgate 6 oz',
    category: 'Aseo Personal',
    weight: 0.38,
    price: 2.98,
    width: 2,
    height: 5.5,
    depth: 1.5,
    volume: 16.5,
    color: '#FF0000',
    emoji: '🪥',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/colgate-cavity-protection-fluoride-toothpaste-6-0-oz/10312168',
    description: 'Pasta dental Colgate protección contra caries, 6 oz.',
    packagingType: 'box',
  },
  {
    id: 'gv-shampoo-12oz',
    name: 'Suave Professionals Shampoo, 12 oz',
    nameEs: 'Champú Suave 12 oz',
    category: 'Aseo Personal',
    weight: 0.75,
    price: 3.48,
    width: 2.5,
    height: 7.5,
    depth: 2.5,
    volume: 46.88,
    color: '#9370DB',
    emoji: '🧴',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/suave-professionals-keratin-infusion-smooth-shampoo-12-oz/456154215',
    description: 'Champú profesional Suave, 12 oz.',
    packagingType: 'bottle',
  },
  {
    id: 'gv-deodorant-1',
    name: 'Secret Deodorant, Invisible Solid, 2.6 oz',
    nameEs: 'Desodorante Secret 2.6 oz',
    category: 'Aseo Personal',
    weight: 0.16,
    price: 4.48,
    width: 2,
    height: 5.5,
    depth: 2,
    volume: 22,
    color: '#708090',
    emoji: '🧴',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/secret-invisible-solid-deodorant-powder-fresh-2-6-oz/10311780',
    description: 'Desodorante Secret invisible sólido, 2.6 oz.',
    packagingType: 'box',
  },
  {
    id: 'gv-body-wash-18oz',
    name: 'Dove Body Wash, Deep Moisture, 18 oz',
    nameEs: 'Gel de Baño Dove 18 oz',
    category: 'Aseo Personal',
    weight: 1.13,
    price: 5.98,
    width: 3.5,
    height: 8,
    depth: 3,
    volume: 84,
    color: '#87CEEB',
    emoji: '🚿',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/dove-body-wash-deep-moisture-18-oz/10312758',
    description: 'Gel de baño Dove hidratación profunda, 18 oz.',
    packagingType: 'bottle',
  },

  // ═══════════ ASEO DEL HOGAR ═══════════
  {
    id: 'gv-detergent-52oz',
    name: 'Great Value Liquid Laundry Detergent, 52 oz',
    nameEs: 'Detergente Líquido para Ropa 52 oz',
    category: 'Aseo del Hogar',
    weight: 3.25,
    price: 4.48,
    width: 5,
    height: 10,
    depth: 3.5,
    volume: 175,
    color: '#00CED1',
    emoji: '🧹',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-liquid-laundry-detergent-original-scent-52-oz/10450597',
    description: 'Detergente líquido para ropa Great Value, 52 oz.',
    packagingType: 'bottle',
  },
  {
    id: 'gv-dish-soap-14oz',
    name: 'Great Value Dish Soap, Lemon Scent, 14 oz',
    nameEs: 'Jabón para Platos Limón 14 oz',
    category: 'Aseo del Hogar',
    weight: 0.88,
    price: 0.98,
    width: 2.5,
    height: 7.5,
    depth: 2.5,
    volume: 46.88,
    color: '#7FFF00',
    emoji: '🧽',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-lemon-scent-dish-soap-14-oz/10450599',
    description: 'Jabón para platos aroma a limón Great Value, 14 oz.',
    packagingType: 'bottle',
  },
  {
    id: 'gv-tp-4pk',
    name: 'Great Value Ultra Strong Toilet Paper, 4 Mega Rolls',
    nameEs: 'Papel Higiénico ×4 rollos',
    category: 'Aseo del Hogar',
    weight: 2.5,
    price: 4.48,
    width: 10,
    height: 4.5,
    depth: 8,
    volume: 360,
    color: '#F5F5F5',
    emoji: '🧻',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-ultra-strong-toilet-paper-4-mega-rolls/456292873',
    description: 'Papel higiénico ultra fuerte Great Value, 4 mega rollos.',
    packagingType: 'box',
  },
  {
    id: 'gv-bleach-1gal',
    name: 'Great Value Disinfecting Bleach, 121 fl oz',
    nameEs: 'Cloro Blanqueador 121 fl oz',
    category: 'Aseo del Hogar',
    weight: 8,
    price: 3.28,
    width: 6,
    height: 11,
    depth: 5.5,
    volume: 363,
    color: '#E0FFFF',
    emoji: '🧴',
    shelfLife: '12 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-disinfecting-bleach-121-fl-oz/10450601',
    description: 'Cloro blanqueador desinfectante Great Value, 121 fl oz.',
    packagingType: 'bottle',
  },
  {
    id: 'gv-salt-26oz',
    name: 'Great Value Iodized Salt, 26 oz',
    nameEs: 'Sal Yodada 26 oz',
    category: 'Aseo del Hogar',
    weight: 1.63,
    price: 0.68,
    width: 3,
    height: 5,
    depth: 2,
    volume: 30,
    color: '#F0F0F0',
    emoji: '🧂',
    shelfLife: '60 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-iodized-salt-26-oz/10450608',
    description: 'Sal yodada Great Value, 26 oz.',
    packagingType: 'jar',
  },
  {
    id: 'gv-vinegar-1gal',
    name: 'Great Value Distilled White Vinegar, 1 gal',
    nameEs: 'Vinagre Blanco Destilado 1 gal',
    category: 'Aseo del Hogar',
    weight: 8.3,
    price: 3.28,
    width: 6,
    height: 11,
    depth: 6,
    volume: 396,
    color: '#FAFAD2',
    emoji: '🫗',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-distilled-white-vinegar-1-gal/10450614',
    description: 'Vinagre blanco destilado Great Value, 1 galón.',
    packagingType: 'bottle',
  },

  // ═══════════ MAS LACTEOS ═══════════
  {
    id: 'gv-condensed-milk-14oz',
    name: 'Great Value Sweetened Condensed Milk, 14 oz',
    nameEs: 'Leche Condensada 14 oz',
    category: 'Lácteos Estables',
    weight: 0.88,
    price: 2.18,
    width: 3,
    height: 4.5,
    depth: 2,
    volume: 27,
    color: '#FFF8DC',
    emoji: '🥛',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-sweetened-condensed-milk-14-oz/10450623',
    description: 'Leche condensada azucarada Great Value, 14 oz.',
    packagingType: 'can',
  },
  {
    id: 'gv-evaporated-milk-12oz',
    name: 'Great Value Evaporated Milk, 12 oz, 6 Pack',
    nameEs: 'Leche Evaporada ×6 latas',
    category: 'Lácteos Estables',
    weight: 4.5,
    price: 6.48,
    width: 9,
    height: 4,
    depth: 5,
    volume: 180,
    color: '#F5F5DC',
    emoji: '🥛',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-evaporated-milk-12-oz-cans-6-count/10450622',
    description: 'Pack de 6 latas de leche evaporada Great Value, 12 oz c/u.',
    packagingType: 'can',
  },
  {
    id: 'gv-parmesan-8oz',
    name: 'Great Value Grated Parmesan Cheese, 8 oz',
    nameEs: 'Queso Parmesano Rallado 8 oz',
    category: 'Lácteos Estables',
    weight: 0.5,
    price: 2.98,
    width: 3,
    height: 5,
    depth: 2.5,
    volume: 37.5,
    color: '#F5DEB3',
    emoji: '🧀',
    shelfLife: '12 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-grated-parmesan-cheese-8-oz/10450624',
    description: 'Queso parmesano rallado Great Value, 8 oz.',
    packagingType: 'jar',
  },
  // QUESO MOZZARELLA REMOVIDO: requiere refrigeracion - no sobrevive 30 dias en barco

  // ═══════════ MAS GRANOS Y CEREALES ═══════════
  {
    id: 'gv-rice-2lb',
    name: 'Great Value Long Grain White Rice, 2 lb',
    nameEs: 'Arroz Blanco 2 lb',
    category: 'Granos y Cereales',
    weight: 2,
    price: 1.58,
    width: 5.5,
    height: 7.5,
    depth: 2,
    volume: 82.5,
    color: '#F5F5DC',
    emoji: '🍚',
    shelfLife: '12 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-long-grain-white-rice-2-lb/10314158',
    description: 'Arroz blanco grano largo Great Value, 2 libras.',
    packagingType: 'bag',
  },
  {
    id: 'gv-elbow-pasta-16oz',
    name: 'Great Value Elbow Macaroni, 16 oz',
    nameEs: 'Coditos Macarrones 16 oz',
    category: 'Granos y Cereales',
    weight: 1,
    price: 1.18,
    width: 3,
    height: 8,
    depth: 2.5,
    volume: 60,
    color: '#FFE4B5',
    emoji: '🍝',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-elbow-macaroni-16-oz/10450638',
    description: 'Coditos macarrones Great Value, 16 oz.',
    packagingType: 'bag',
  },
  {
    id: 'gv-pen pasta-16oz',
    name: 'Great Value Penne Pasta, 16 oz',
    nameEs: 'Penne Pasta 16 oz',
    category: 'Granos y Cereales',
    weight: 1,
    price: 1.18,
    width: 3,
    height: 8,
    depth: 2.5,
    volume: 60,
    color: '#FFDEAD',
    emoji: '🍝',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-penne-pasta-16-oz/10450636',
    description: 'Penne pasta Great Value, 16 oz.',
    packagingType: 'bag',
  },
  {
    id: 'gv-cornstarch-16oz',
    name: 'Great Value Cornstarch, 16 oz',
    nameEs: 'Maicena 16 oz',
    category: 'Granos y Cereales',
    weight: 1,
    price: 1.48,
    width: 3,
    height: 5.5,
    depth: 2,
    volume: 33,
    color: '#FFFFFF',
    emoji: '🌽',
    shelfLife: '18 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-cornstarch-16-oz/10450612',
    description: 'Maicena Great Value, 16 oz.',
    packagingType: 'bag',
  },
  {
    id: 'gv-quinoa-12oz',
    name: 'Great Value Tri-Color Quinoa, 12 oz',
    nameEs: 'Quinoa Tricolor 12 oz',
    category: 'Granos y Cereales',
    weight: 0.75,
    price: 3.48,
    width: 5,
    height: 7,
    depth: 2,
    volume: 70,
    color: '#DAA520',
    emoji: '🌾',
    shelfLife: '18 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-tri-color-quinoa-12-oz/456920737',
    description: 'Quinoa tricolor Great Value, 12 oz.',
    packagingType: 'bag',
  },
  {
    id: 'gv-gnocchi-16oz',
    name: 'Great Value Potato Gnocchi, 16 oz',
    nameEs: 'Nquis de Papa 16 oz',
    category: 'Granos y Cereales',
    weight: 1,
    price: 1.98,
    width: 4,
    height: 6,
    depth: 2.5,
    volume: 60,
    color: '#FFEFD5',
    emoji: '🥔',
    shelfLife: '18 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-potato-gnocchi-16-oz/456920740',
    description: 'Nquis de papa Great Value, 16 oz.',
    packagingType: 'bag',
  },

  // ═══════════ MAS GRANOS Y CEREALES ═══════════
  {
    id: 'gv-rice-10lb',
    name: 'Great Value Long Grain White Rice, 10 lb',
    nameEs: 'Arroz Blanco Grano Largo 10 lb',
    category: 'Granos y Cereales',
    weight: 10,
    price: 6.48,
    width: 8,
    height: 12,
    depth: 3,
    volume: 288,
    color: '#F5F5DC',
    emoji: '🍚',
    shelfLife: '12 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-long-grain-white-rice-10-lb/10314159',
    description: 'Arroz blanco grano largo Great Value, 10 libras.',
    packagingType: 'bag',
  },
  {
    id: 'gv-fideo-16oz',
    name: 'Great Value Thin Spaghetti, 16 oz',
    nameEs: 'Fideo Delgado 16 oz',
    category: 'Granos y Cereales',
    weight: 1,
    price: 1.18,
    width: 3,
    height: 10,
    depth: 2.5,
    volume: 75,
    color: '#FFE4B5',
    emoji: '🍝',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-thin-spaghetti-16-oz/10450640',
    description: 'Fideo delgado Great Value, 16 oz.',
    packagingType: 'bag',
  },
  {
    id: 'gv-pinto-beans-4lb',
    name: 'Great Value Dried Pinto Beans, 4 lb',
    nameEs: 'Frijoles Pintos Secos 4 lb',
    category: 'Granos y Cereales',
    weight: 4,
    price: 4.28,
    width: 8,
    height: 10,
    depth: 3,
    volume: 240,
    color: '#8B6914',
    emoji: '🫘',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-dried-pinto-beans-4-lb/155982625',
    description: 'Frijoles pintos secos Great Value, 4 libras.',
    packagingType: 'bag',
  },
  {
    id: 'gv-navy-beans-2lb',
    name: 'Great Value Dried Navy Beans, 2 lb',
    nameEs: 'Frijoles Blancos Secos 2 lb',
    category: 'Granos y Cereales',
    weight: 2,
    price: 2.62,
    width: 7,
    height: 9,
    depth: 2.5,
    volume: 157.5,
    color: '#F5F5F5',
    emoji: '🫘',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-dried-navy-beans-2-lb/155982627',
    description: 'Frijoles blancos secos Great Value, 2 libras.',
    packagingType: 'bag',
  },
  {
    id: 'gv-flour-10lb',
    name: 'Great Value All-Purpose Flour, 10 lb',
    nameEs: 'Harina de Trigo Todo Uso 10 lb',
    category: 'Granos y Cereales',
    weight: 10,
    price: 6.18,
    width: 8,
    height: 12,
    depth: 3,
    volume: 288,
    color: '#FFF8DC',
    emoji: '🌾',
    shelfLife: '12 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-all-purpose-flour-10-lb/10450620',
    description: 'Harina de trigo todo uso Great Value, 10 libras.',
    packagingType: 'bag',
  },
  {
    id: 'gv-brown-rice-2lb',
    name: 'Great Value Long Grain Brown Rice, 2 lb',
    nameEs: 'Arroz Integral 2 lb',
    category: 'Granos y Cereales',
    weight: 2,
    price: 2.18,
    width: 5.5,
    height: 7.5,
    depth: 2,
    volume: 82.5,
    color: '#D2B48C',
    emoji: '🍚',
    shelfLife: '12 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-long-grain-brown-rice-2-lb/10314160',
    description: 'Arroz integral grano largo Great Value, 2 libras.',
    packagingType: 'bag',
  },

  // ═══════════ MAS ENLATADOS ═══════════
  {
    id: 'gv-green-beans-3pk',
    name: 'Great Value Cut Green Beans, 14.5 oz, 3 Pack',
    nameEs: 'Habichuelas Verdes ×3 latas',
    category: 'Enlatados',
    weight: 2.7,
    price: 2.18,
    width: 7,
    height: 5,
    depth: 3.5,
    volume: 122.5,
    color: '#32CD32',
    emoji: '🥫',
    shelfLife: '36 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-cut-green-beans-14-5-oz-cans-3-count/10450588',
    description: 'Pack de 3 latas de habichuelas verdes Great Value.',
    packagingType: 'can',
  },
  {
    id: 'gv-peas-3pk',
    name: 'Great Value Sweet Peas, 15 oz, 3 Pack',
    nameEs: 'Guisantes Dulces ×3 latas',
    category: 'Enlatados',
    weight: 2.8,
    price: 2.18,
    width: 7,
    height: 5,
    depth: 3.5,
    volume: 122.5,
    color: '#90EE90',
    emoji: '🥫',
    shelfLife: '36 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-sweet-peas-15-oz-cans-3-count/10450592',
    description: 'Pack de 3 latas de guisantes dulces Great Value.',
    packagingType: 'can',
  },
  {
    id: 'gv-mixed-veg-3pk',
    name: 'Great Value Mixed Vegetables, 15.25 oz, 3 Pack',
    nameEs: 'Vegetales Mixtos ×3 latas',
    category: 'Enlatados',
    weight: 2.9,
    price: 2.48,
    width: 7,
    height: 5,
    depth: 3.5,
    volume: 122.5,
    color: '#FF6347',
    emoji: '🥫',
    shelfLife: '36 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-mixed-vegetables-15-25-oz-cans-3-count/10450594',
    description: 'Pack de 3 latas de vegetales mixtos Great Value.',
    packagingType: 'can',
  },
  {
    id: 'gv-chili-3pk',
    name: 'Great Value Chili with Beans, 15 oz, 3 Pack',
    nameEs: 'Chili con Frijoles ×3 latas',
    category: 'Enlatados',
    weight: 2.8,
    price: 3.28,
    width: 7,
    height: 5,
    depth: 3.5,
    volume: 122.5,
    color: '#8B0000',
    emoji: '🌶️',
    shelfLife: '36 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-chili-with-beans-15-oz-cans-3-count/10450591',
    description: 'Pack de 3 latas de chili con frijoles Great Value.',
    packagingType: 'can',
  },
  {
    id: 'gv-tuna-oil-3pk',
    name: 'Great Value Tuna in Oil, 5 oz, 3 Pack',
    nameEs: 'Atun en Aceite ×3 latas',
    category: 'Enlatados',
    weight: 1,
    price: 4.48,
    width: 6,
    height: 3,
    depth: 3.5,
    volume: 63,
    color: '#4682B4',
    emoji: '🐟',
    shelfLife: '36 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-chunk-light-tuna-in-oil-5-oz-cans-3-count/10450589',
    description: 'Pack de 3 latas de atun en aceite Great Value.',
    packagingType: 'can',
  },
  {
    id: 'gv-potatoes-3pk',
    name: 'Great Value Whole White Potatoes, 15.25 oz, 3 Pack',
    nameEs: 'Papas Enteras ×3 latas',
    category: 'Enlatados',
    weight: 2.9,
    price: 2.48,
    width: 7,
    height: 5,
    depth: 3.5,
    volume: 122.5,
    color: '#DEB887',
    emoji: '🥔',
    shelfLife: '36 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-whole-white-potatoes-15-25-oz-cans-3-count/456294567',
    description: 'Pack de 3 latas de papas enteras Great Value.',
    packagingType: 'can',
  },
  {
    id: 'gv-chicken-5oz',
    name: 'Great Value Canned Chicken Breast, 5 oz, 3 Pack',
    nameEs: 'Pechuga de Pollo Enlatada ×3',
    category: 'Enlatados',
    weight: 0.94,
    price: 5.48,
    width: 5,
    height: 3.5,
    depth: 3,
    volume: 52.5,
    color: '#FFD700',
    emoji: '🍗',
    shelfLife: '36 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-canned-chicken-breast-5-oz-cans-3-count/456294569',
    description: 'Pack de 3 latas de pechuga de pollo Great Value.',
    packagingType: 'can',
  },

  // ═══════════ SEMILLAS Y FRUTOS SECOS ═══════════
  {
    id: 'gv-sunflower-seeds-8oz',
    name: 'Great Value Roasted Sunflower Seeds, 8.75 oz',
    nameEs: 'Semillas de Girasol Tostadas 8.75 oz',
    category: 'Semillas y Frutos Secos',
    weight: 0.55,
    price: 2.48,
    width: 5,
    height: 7,
    depth: 2.5,
    volume: 87.5,
    color: '#2F4F4F',
    emoji: '🌻',
    shelfLife: '9 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-roasted-sunflower-seeds-8-75-oz/456920742',
    description: 'Semillas de girasol tostadas con sal, 8.75 oz.',
    packagingType: 'bag',
  },
  {
    id: 'gv-peanuts-16oz',
    name: 'Great Value Dry Roasted Peanuts, 16 oz',
    nameEs: 'Cacahuates Tostados Secos 16 oz',
    category: 'Semillas y Frutos Secos',
    weight: 1,
    price: 3.28,
    width: 5.5,
    height: 7.5,
    depth: 2.5,
    volume: 103.13,
    color: '#D2691E',
    emoji: '🥜',
    shelfLife: '9 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-dry-roasted-peanuts-16-oz/456920744',
    description: 'Cacahuates tostados secos con sal, 16 oz.',
    packagingType: 'bag',
  },
  {
    id: 'gv-mixed-nuts-10oz',
    name: 'Great Value Mixed Nuts, 10 oz',
    nameEs: 'Frutos Secos Mezclados 10 oz',
    category: 'Semillas y Frutos Secos',
    weight: 0.63,
    price: 5.48,
    width: 4.5,
    height: 6.5,
    depth: 3,
    volume: 87.75,
    color: '#8B4513',
    emoji: '🌰',
    shelfLife: '9 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-mixed-nuts-10-oz/456920746',
    description: 'Mezcla de frutos secos, 10 oz.',
    packagingType: 'bag',
  },
  {
    id: 'gv-raisins-15oz',
    name: 'Great Value Raisins, 15 oz',
    nameEs: 'Pasas 15 oz',
    category: 'Semillas y Frutos Secos',
    weight: 0.94,
    price: 3.28,
    width: 5,
    height: 7,
    depth: 2,
    volume: 70,
    color: '#4B0082',
    emoji: '🍇',
    shelfLife: '12 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-raisins-15-oz/10450625',
    description: 'Pasas Great Value, 15 oz.',
    packagingType: 'bag',
  },
  {
    id: 'gv-almonds-6oz',
    name: 'Great Value Sliced Almonds, 6 oz',
    nameEs: 'Almendras Rebanadas 6 oz',
    category: 'Semillas y Frutos Secos',
    weight: 0.38,
    price: 4.48,
    width: 3.5,
    height: 5,
    depth: 2,
    volume: 35,
    color: '#DEB887',
    emoji: '🌰',
    shelfLife: '12 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-sliced-almonds-6-oz/456920748',
    description: 'Almendras rebanadas Great Value, 6 oz.',
    packagingType: 'bag',
  },
  {
    id: 'gv-pumpkin-seeds-5oz',
    name: 'Great Value Roasted Pumpkin Seeds, 5 oz',
    nameEs: 'Semillas de Calabaza Tostadas 5 oz',
    category: 'Semillas y Frutos Secos',
    weight: 0.31,
    price: 2.48,
    width: 4,
    height: 5.5,
    depth: 2,
    volume: 44,
    color: '#556B2F',
    emoji: '🎃',
    shelfLife: '9 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-roasted-pumpkin-seeds-5-oz/456920750',
    description: 'Semillas de calabaza tostadas con sal, 5 oz.',
    packagingType: 'bag',
  },

  // ═══════════ CONDIMENTOS Y SALSAS ═══════════
  {
    id: 'gv-ketchup-20oz',
    name: 'Great Value Tomato Ketchup, 20 oz',
    nameEs: 'Ketchup 20 oz',
    category: 'Condimentos y Salsas',
    weight: 1.25,
    price: 1.68,
    width: 2.5,
    height: 7.5,
    depth: 2.5,
    volume: 46.88,
    color: '#FF0000',
    emoji: '🍅',
    shelfLife: '15 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-tomato-ketchup-20-oz/10450626',
    description: 'Ketchup de tomate Great Value, 20 oz.',
    packagingType: 'bottle',
  },
  {
    id: 'gv-mayo-30oz',
    name: 'Great Value Real Mayonnaise, 30 oz',
    nameEs: 'Mayonesa 30 oz',
    category: 'Condimentos y Salsas',
    weight: 1.88,
    price: 3.28,
    width: 3,
    height: 8,
    depth: 3,
    volume: 72,
    color: '#FAFAD2',
    emoji: '🥚',
    shelfLife: '6 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-real-mayonnaise-30-oz/10450627',
    description: 'Mayonesa real Great Value, 30 oz.',
    packagingType: 'jar',
  },
  {
    id: 'gv-mustard-12oz',
    name: 'Great Value Yellow Mustard, 12 oz',
    nameEs: 'Mostaza Amarilla 12 oz',
    category: 'Condimentos y Salsas',
    weight: 0.75,
    price: 1.28,
    width: 2,
    height: 6,
    depth: 2,
    volume: 24,
    color: '#FFD700',
    emoji: '🟡',
    shelfLife: '12 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-yellow-mustard-12-oz/10450628',
    description: 'Mostaza amarilla Great Value, 12 oz.',
    packagingType: 'bottle',
  },
  {
    id: 'gv-hot-sauce-5oz',
    name: 'Great Value Hot Sauce, 5 oz',
    nameEs: 'Salsa Picante 5 oz',
    category: 'Condimentos y Salsas',
    weight: 0.31,
    price: 0.98,
    width: 1.5,
    height: 6.5,
    depth: 1.5,
    volume: 14.63,
    color: '#FF4500',
    emoji: '🌶️',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-hot-sauce-5-oz/10450629',
    description: 'Salsa picante tipo Tabasco Great Value, 5 oz.',
    packagingType: 'bottle',
  },
  {
    id: 'gv-soy-sauce-10oz',
    name: 'Great Value Soy Sauce, 10 oz',
    nameEs: 'Salsa de Soya 10 oz',
    category: 'Condimentos y Salsas',
    weight: 0.63,
    price: 0.98,
    width: 2,
    height: 6,
    depth: 2,
    volume: 24,
    color: '#3C1414',
    emoji: '🫗',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-soy-sauce-10-oz/10450630',
    description: 'Salsa de soya Great Value, 10 oz.',
    packagingType: 'bottle',
  },
  {
    id: 'gv-sazon-4pk',
    name: 'Goya Sazon with Saffron, 1.41 oz, 4 Pack',
    nameEs: 'Sazon Goya con Azafran ×4',
    category: 'Condimentos y Salsas',
    weight: 0.35,
    price: 2.98,
    width: 6,
    height: 3,
    depth: 2,
    volume: 36,
    color: '#FFA500',
    emoji: '✨',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/goya-sazon-con-azafran-1-41-oz-4-count/10314275',
    description: 'Pack de 4 sobres de sazon Goya con azafran.',
    packagingType: 'box',
  },
  {
    id: 'gv-adobo-4pk',
    name: 'Goya Adobo All Purpose Seasoning, 8.5 oz, 2 Pack',
    nameEs: 'Adobo Goya Todo Uso ×2',
    category: 'Condimentos y Salsas',
    weight: 1.06,
    price: 3.98,
    width: 4,
    height: 5.5,
    depth: 2.5,
    volume: 55,
    color: '#D2691E',
    emoji: '✨',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/goya-adobo-all-purpose-seasoning-8-5-oz-2-count/10314277',
    description: 'Pack de 2 sazonadores adobo Goya todo uso, 8.5 oz c/u.',
    packagingType: 'jar',
  },
  {
    id: 'gv-garlic-powder-2oz',
    name: 'Great Value Garlic Powder, 2.75 oz',
    nameEs: 'Ajo en Polvo 2.75 oz',
    category: 'Condimentos y Salsas',
    weight: 0.17,
    price: 1.28,
    width: 2.5,
    height: 4.5,
    depth: 1.5,
    volume: 16.88,
    color: '#FFFACD',
    emoji: '🧄',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-garlic-powder-2-75-oz/10450631',
    description: 'Ajo en polvo Great Value, 2.75 oz.',
    packagingType: 'jar',
  },
  {
    id: 'gv-onion-powder-2oz',
    name: 'Great Value Onion Powder, 2.75 oz',
    nameEs: 'Cebolla en Polvo 2.75 oz',
    category: 'Condimentos y Salsas',
    weight: 0.17,
    price: 1.28,
    width: 2.5,
    height: 4.5,
    depth: 1.5,
    volume: 16.88,
    color: '#FAF0E6',
    emoji: '🧅',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-onion-powder-2-75-oz/10450632',
    description: 'Cebolla en polvo Great Value, 2.75 oz.',
    packagingType: 'jar',
  },
  {
    id: 'gv-black-pepper-1oz',
    name: 'Great Value Black Pepper, 1.5 oz',
    nameEs: 'Pimienta Negra 1.5 oz',
    category: 'Condimentos y Salsas',
    weight: 0.09,
    price: 1.48,
    width: 2,
    height: 4,
    depth: 1.5,
    volume: 12,
    color: '#2F2F2F',
    emoji: '🌶️',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-black-pepper-1-5-oz/10450633',
    description: 'Pimienta negra molida Great Value, 1.5 oz.',
    packagingType: 'jar',
  },
  {
    id: 'gv-oregano-1oz',
    name: 'Great Value Oregano, 0.7 oz',
    nameEs: 'Oregano 0.7 oz',
    category: 'Condimentos y Salsas',
    weight: 0.04,
    price: 1.28,
    width: 2,
    height: 3.5,
    depth: 1.5,
    volume: 10.5,
    color: '#228B22',
    emoji: '🌿',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-oregano-leaves-0-7-oz/10450634',
    description: 'Oregano Great Value, 0.7 oz.',
    packagingType: 'jar',
  },
  {
    id: 'gv-comino-1oz',
    name: 'Great Value Ground Cumin, 1.75 oz',
    nameEs: 'Comino Molido 1.75 oz',
    category: 'Condimentos y Salsas',
    weight: 0.11,
    price: 1.28,
    width: 2,
    height: 4,
    depth: 1.5,
    volume: 12,
    color: '#B8860B',
    emoji: '✨',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-ground-cumin-1-75-oz/10450635',
    description: 'Comino molido Great Value, 1.75 oz.',
    packagingType: 'jar',
  },

  // ═══════════ MAS CONDIMENTOS Y SALSAS ═══════════
  {
    id: 'gv-salsa-verde-7oz',
    name: 'La Costena Salsa Verde, 7 oz, 3 Pack',
    nameEs: 'Salsa Verde ×3 frascos',
    category: 'Condimentos y Salsas',
    weight: 1.3,
    price: 3.48,
    width: 6,
    height: 4,
    depth: 4,
    volume: 96,
    color: '#66BB6A',
    emoji: '🫗',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/la-costena-salsa-verde-7-oz-jar-3-count/20814035',
    description: 'Pack de 3 frascos de salsa verde La Costena.',
    packagingType: 'jar',
  },
  {
    id: 'gv-adobo-11oz',
    name: 'Goya Adobo All Purpose Seasoning, 11 oz',
    nameEs: 'Adobo Completo 11 oz',
    category: 'Condimentos y Salsas',
    weight: 0.69,
    price: 2.98,
    width: 3,
    height: 6,
    depth: 2,
    volume: 36,
    color: '#FF8F00',
    emoji: '🧂',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/goya-adobo-all-purpose-seasoning-11-oz/10314161',
    description: 'Adobo completo sazón Goya, 11 oz.',
    packagingType: 'bag',
  },
  {
    id: 'gv-sazon-11oz',
    name: 'Goya Sazon with Coriander & Annatto, 10.5 oz',
    nameEs: 'Sazón Goya con Culantro y Achiote',
    category: 'Condimentos y Salsas',
    weight: 0.66,
    price: 3.48,
    width: 5,
    height: 7,
    depth: 2.5,
    volume: 87.5,
    color: '#FF6F00',
    emoji: '🧂',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/goya-sazon-with-coriander-and-annatto-10-5-oz/10314162',
    description: 'Sazón Goya con culantro y achiote.',
    packagingType: 'box',
  },
  {
    id: 'gv-cumin-1oz',
    name: 'Great Value Ground Cumin, 1.75 oz',
    nameEs: 'Comino Molido 1.75 oz',
    category: 'Condimentos y Salsas',
    weight: 0.11,
    price: 1.28,
    width: 2,
    height: 3.5,
    depth: 1.5,
    volume: 10.5,
    color: '#8D6E63',
    emoji: '🧂',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-ground-cumin-1-75-oz/10450633',
    description: 'Comino molido Great Value, 1.75 oz.',
    packagingType: 'bag',
  },

  // ═══════════ MAS BEBIDAS ═══════════
  {
    id: 'gv-nesquik-21oz',
    name: 'Nesquik Chocolate Powder, 21.8 oz',
    nameEs: 'Nesquik en Polvo Chocolate 21.8 oz',
    category: 'Bebidas y Café',
    weight: 1.36,
    price: 4.98,
    width: 5.5,
    height: 7.5,
    depth: 2.5,
    volume: 103.13,
    color: '#8B4513',
    emoji: '🍫',
    shelfLife: '18 meses',
    walmartUrl: 'https://www.walmart.com/ip/nesquik-chocolate-powder-21-8-oz/10313810',
    description: 'Nesquik en polvo sabor chocolate, 21.8 oz.',
    packagingType: 'bag',
  },
  {
    id: 'gv-tea-bags-100',
    name: 'Great Value Black Tea Bags, 100 Count',
    nameEs: 'Té Negro ×100 sobres',
    category: 'Bebidas y Café',
    weight: 0.31,
    price: 2.48,
    width: 4,
    height: 5.5,
    depth: 2.5,
    volume: 55,
    color: '#8B6914',
    emoji: '🫖',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-black-tea-bags-100-count/10450639',
    description: 'Té negro en sobres Great Value, 100 sobres.',
    packagingType: 'box',
  },
  {
    id: 'gv-lemonade-7pk',
    name: 'Great Value Lemonade Drink Mix, 7 Pack',
    nameEs: 'Limonada en Polvo ×7 sobres',
    category: 'Bebidas y Café',
    weight: 0.44,
    price: 2.48,
    width: 7,
    height: 4,
    depth: 2,
    volume: 56,
    color: '#FFF44F',
    emoji: '🍋',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-lemonade-drink-mix-7-count/456294571',
    description: 'Limonada en polvo Great Value, 7 sobres.',
  },
  {
    id: 'gv-tang-11oz',
    name: 'Tang Orange Drink Mix, 11.2 oz',
    nameEs: 'Tang Sabor Naranja 11.2 oz',
    category: 'Bebidas y Café',
    weight: 0.7,
    price: 3.48,
    width: 4,
    height: 7,
    depth: 2.5,
    volume: 70,
    color: '#FF8C00',
    emoji: '🍊',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/tang-orange-drink-mix-11-2-oz/10314710',
    description: 'Tang sabor naranja en polvo, 11.2 oz.',
  },

  // ═══════════ MAS SNACKS ═══════════
  {
    id: 'gv-cookies-12oz',
    name: 'Great Value Chocolate Chip Cookies, 12.4 oz',
    nameEs: 'Galletas con Chispas de Chocolate 12.4 oz',
    category: 'Snacks y Desayuno',
    weight: 0.78,
    price: 2.48,
    width: 7,
    height: 8,
    depth: 2.5,
    volume: 140,
    color: '#8B4513',
    emoji: '🍪',
    shelfLife: '9 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-chocolate-chip-cookies-12-4-oz/10450620',
    description: 'Galletas con chispas de chocolate Great Value, 12.4 oz.',
  },
  {
    id: 'gv-pretzels-16oz',
    name: 'Great Value Pretzel Sticks, 16 oz',
    nameEs: 'Palitos de Pretzel 16 oz',
    category: 'Snacks y Desayuno',
    weight: 1,
    price: 2.48,
    width: 6,
    height: 9,
    depth: 3,
    volume: 162,
    color: '#DEB887',
    emoji: '🥨',
    shelfLife: '9 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-pretzel-sticks-16-oz/456294573',
    description: 'Palitos de pretzel salados Great Value, 16 oz.',
  },
  {
    id: 'gv-fruit-snacks-10pk',
    name: 'Great Value Fruit Snacks, 0.9 oz, 10 Pack',
    nameEs: 'Snacks de Fruta ×10 bolsitas',
    category: 'Snacks y Desayuno',
    weight: 0.56,
    price: 2.48,
    width: 6,
    height: 5,
    depth: 2.5,
    volume: 75,
    color: '#FF69B4',
    emoji: '🍓',
    shelfLife: '9 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-fruit-snacks-0-9-oz-pouches-10-count/456294575',
    description: 'Snacks de fruta Great Value, 10 bolsitas.',
  },
  {
    id: 'gv-graham-crackers-14oz',
    name: 'Great Value Honey Graham Crackers, 14.4 oz',
    nameEs: 'Galletas Graham con Miel 14.4 oz',
    category: 'Snacks y Desayuno',
    weight: 0.9,
    price: 2.48,
    width: 8,
    height: 8,
    depth: 2,
    volume: 128,
    color: '#DAA520',
    emoji: '🍪',
    shelfLife: '9 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-honey-graham-crackers-14-4-oz/10450621',
    description: 'Galletas graham con miel Great Value, 14.4 oz.',
  },
  {
    id: 'gv-popcorn-4pk',
    name: 'Great Value Microwave Popcorn Butter, 3.2 oz, 4 Pack',
    nameEs: 'Palomitas de Microondas ×4',
    category: 'Snacks y Desayuno',
    weight: 0.8,
    price: 2.48,
    width: 7,
    height: 4.5,
    depth: 2.5,
    volume: 78.75,
    color: '#FFD700',
    emoji: '🍿',
    shelfLife: '12 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-microwave-popcorn-butter-3-2-oz-4-count/456294577',
    description: 'Palomitas de microondas sabor mantequilla, 4 paquetes.',
  },

  // ═══════════ MAS ACEITES ═══════════
  {
    id: 'gv-olive-oil-16oz',
    name: 'Great Value 100% Pure Olive Oil, 16.9 fl oz',
    nameEs: 'Aceite de Oliva 16.9 fl oz',
    category: 'Aceites y Grasas',
    weight: 1.06,
    price: 4.98,
    width: 2.5,
    height: 9.5,
    depth: 2.5,
    volume: 59.38,
    color: '#808000',
    emoji: '🫒',
    shelfLife: '18 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-100-pure-olive-oil-16-9-fl-oz/10450597',
    description: 'Aceite de oliva puro Great Value, 16.9 fl oz.',
  },
  {
    id: 'gv-canola-oil-48oz',
    name: 'Great Value Canola Oil, 48 fl oz',
    nameEs: 'Aceite de Canola 48 fl oz',
    category: 'Aceites y Grasas',
    weight: 3,
    price: 3.68,
    width: 3.5,
    height: 10.5,
    depth: 3.5,
    volume: 128.63,
    color: '#FFD700',
    emoji: '🫒',
    shelfLife: '18 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-canola-oil-48-fl-oz/456294579',
    description: 'Aceite de canola Great Value, 48 fl oz.',
  },

  // ═══════════ MAS AZUCARES ═══════════
  {
    id: 'gv-brown-sugar-2lb',
    name: 'Great Value Brown Sugar, 2 lb',
    nameEs: 'Azúcar Morena 2 lb',
    category: 'Azucares y Endulzantes',
    weight: 2,
    price: 1.78,
    width: 5.5,
    height: 7,
    depth: 2,
    volume: 77,
    color: '#8B4513',
    emoji: '🍬',
    shelfLife: '18 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-brown-sugar-2-lb/10450608',
    description: 'Azucar morena Great Value, 2 libras.',
  },
  {
    id: 'gv-powdered-sugar-2lb',
    name: 'Great Value Powdered Sugar, 2 lb',
    nameEs: 'Azúcar Glass 2 lb',
    category: 'Azucares y Endulzantes',
    weight: 2,
    price: 2.28,
    width: 5.5,
    height: 7.5,
    depth: 2.5,
    volume: 103.13,
    color: '#F0F0F0',
    emoji: '🍬',
    shelfLife: '18 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-powdered-sugar-2-lb/10450610',
    description: 'Azucar glass Great Value, 2 libras.',
  },
  {
    id: 'gv-Equal-200pk',
    name: 'Equal Sweetener, 200 Count',
    nameEs: 'Edulcorante Equal ×200 sobres',
    category: 'Azucares y Endulzantes',
    weight: 0.38,
    price: 6.98,
    width: 6,
    height: 4.5,
    depth: 2.5,
    volume: 67.5,
    color: '#4169E1',
    emoji: '🍬',
    shelfLife: '36 meses',
    walmartUrl: 'https://www.walmart.com/ip/equal-original-sweetener-200-count/10311829',
    description: 'Edulcorante Equal en sobres, 200 sobres.',
  },

  // ═══════════ CHOCOLATES Y DULCES ═══════════
  {
    id: 'hv-choco-bar-155',
    name: 'Hershey Milk Chocolate Bar, 1.55 oz',
    nameEs: 'Chocolate con Leche Hershey 1.55 oz',
    category: 'Chocolates y Dulces',
    weight: 0.19,
    price: 1.28,
    width: 5.5,
    height: 0.25,
    depth: 2.25,
    volume: 3.09,
    color: '#5C3317',
    emoji: '🍫',
    shelfLife: '12 meses',
    walmartUrl: 'https://www.walmart.com/ip/hershey-milk-chocolate-candy-bar-1-55-oz/10315345',
    description: 'Barra de chocolate con leche Hershey, 1.55 oz.',
    packagingType: 'bar',
  },
  {
    id: 'hv-choco-6pk',
    name: 'Hershey Milk Chocolate Bars, 6 Pack',
    nameEs: 'Chocolate con Leche Hershey ×6',
    category: 'Chocolates y Dulces',
    weight: 1.14,
    price: 5.48,
    width: 8,
    height: 1,
    depth: 5,
    volume: 40,
    color: '#6B3A2A',
    emoji: '🍫',
    shelfLife: '12 meses',
    walmartUrl: 'https://www.walmart.com/ip/hershey-milk-chocolate-candy-bars-6-count/10450546',
    description: 'Pack de 6 barras de chocolate con leche Hershey.',
    packagingType: 'box',
  },
  {
    id: 'gv-choco-chips-12oz',
    name: 'Great Value Semi-Sweet Chocolate Chips, 12 oz',
    nameEs: 'Chispas de Chocolate Semi-Amargo 12 oz',
    category: 'Chocolates y Dulces',
    weight: 0.75,
    price: 2.48,
    width: 6,
    height: 7,
    depth: 2,
    volume: 84,
    color: '#3E2723',
    emoji: '🍫',
    shelfLife: '12 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-semi-sweet-chocolate-chips-12-oz/10450643',
    description: 'Chispas de chocolate semi-amargo Great Value, 12 oz.',
    packagingType: 'bag',
  },
  {
    id: 'gv-white-choco-chips',
    name: 'Great Value White Chocolate Chips, 10 oz',
    nameEs: 'Chispas de Chocolate Blanco 10 oz',
    category: 'Chocolates y Dulces',
    weight: 0.63,
    price: 2.28,
    width: 6,
    height: 6.5,
    depth: 2,
    volume: 78,
    color: '#FFF8DC',
    emoji: '🍫',
    shelfLife: '12 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-white-chocolate-chips-10-oz/456294581',
    description: 'Chispas de chocolate blanco Great Value, 10 oz.',
    packagingType: 'bag',
  },
  {
    id: 'gv-butterscotch-chips',
    name: 'Great Value Butterscotch Chips, 11 oz',
    nameEs: 'Chispas de Caramelo 11 oz',
    category: 'Chocolates y Dulces',
    weight: 0.69,
    price: 2.48,
    width: 6,
    height: 6.5,
    depth: 2,
    volume: 78,
    color: '#DAA520',
    emoji: '🍬',
    shelfLife: '12 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-butterscotch-chips-11-oz/456294583',
    description: 'Chispas de caramelo Great Value, 11 oz.',
    packagingType: 'bag',
  },
  {
    id: 'mm-milk-choco-10oz',
    name: 'M&M Milk Chocolate Candy, 10.7 oz',
    nameEs: 'M&M Chocolate con Leche 10.7 oz',
    category: 'Chocolates y Dulces',
    weight: 0.67,
    price: 3.98,
    width: 4,
    height: 7.5,
    depth: 2,
    volume: 60,
    color: '#DEB887',
    emoji: '🟤',
    shelfLife: '12 meses',
    walmartUrl: 'https://www.walmart.com/ip/m-ms-milk-chocolate-candy-10-7-oz/10315350',
    description: 'M&M chocolate con leche, 10.7 oz.',
    packagingType: 'bag',
  },
  {
    id: 'snickers-6pk',
    name: 'Snickers Candy Bars, 1.86 oz, 6 Pack',
    nameEs: 'Barras Snickers ×6',
    category: 'Chocolates y Dulces',
    weight: 0.7,
    price: 3.48,
    width: 7,
    height: 1.5,
    depth: 4,
    volume: 42,
    color: '#8B4513',
    emoji: '🍫',
    shelfLife: '9 meses',
    walmartUrl: 'https://www.walmart.com/ip/snickers-candy-bars-1-86-oz-6-count/10315355',
    description: 'Pack de 6 barras de caramelo Snickers.',
    packagingType: 'box',
  },
  {
    id: 'reese-cups-6pk',
    name: 'Reese Peanut Butter Cups, 1.5 oz, 6 Pack',
    nameEs: 'Reese Cups Mantequilla de Cacahuete ×6',
    category: 'Chocolates y Dulces',
    weight: 0.56,
    price: 3.28,
    width: 7,
    height: 1,
    depth: 4,
    volume: 28,
    color: '#D2691E',
    emoji: '🍫',
    shelfLife: '9 meses',
    walmartUrl: 'https://www.walmart.com/ip/reese-peanut-butter-cups-1-5-oz-6-count/10315358',
    description: 'Pack de 6 tazas de mantequilla de cacahuete Reese.',
    packagingType: 'box',
  },
  {
    id: 'kit-kat-6pk',
    name: 'Kit Kat Candy Bars, 1.5 oz, 6 Pack',
    nameEs: 'Barras Kit Kat ×6',
    category: 'Chocolates y Dulces',
    weight: 0.56,
    price: 3.28,
    width: 7,
    height: 1,
    depth: 4,
    volume: 28,
    color: '#DC143C',
    emoji: '🍫',
    shelfLife: '9 meses',
    walmartUrl: 'https://www.walmart.com/ip/kit-kat-candy-bars-1-5-oz-6-count/10315362',
    description: 'Pack de 6 barras Kit Kat.',
    packagingType: 'box',
  },
  {
    id: 'gv-candy-corn-15oz',
    name: 'Great Value Candy Corn, 15 oz',
    nameEs: 'Candy Corn Dulce 15 oz',
    category: 'Chocolates y Dulces',
    weight: 0.94,
    price: 2.48,
    width: 7,
    height: 7,
    depth: 2.5,
    volume: 122.5,
    color: '#FF8C00',
    emoji: '🌽',
    shelfLife: '12 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-candy-corn-15-oz/10450644',
    description: 'Candy corn Great Value, 15 oz.',
    packagingType: 'bag',
  },
  {
    id: 'jolly-rancher-13oz',
    name: 'Jolly Rancher Hard Candy, 13 oz',
    nameEs: 'Caramelos Jolly Rancher 13 oz',
    category: 'Chocolates y Dulces',
    weight: 0.81,
    price: 2.98,
    width: 6,
    height: 7,
    depth: 2,
    volume: 84,
    color: '#FF4500',
    emoji: '🍬',
    shelfLife: '18 meses',
    walmartUrl: 'https://www.walmart.com/ip/jolly-rancher-hard-candy-13-oz/10315370',
    description: 'Caramelos duros Jolly Rancher, 13 oz.',
    packagingType: 'bag',
  },
  {
    id: 'twizzlers-16oz',
    name: 'Twizzlers Strawberry Twists, 16 oz',
    nameEs: 'Twizzlers Fresa 16 oz',
    category: 'Chocolates y Dulces',
    weight: 1,
    price: 2.48,
    width: 7,
    height: 7,
    depth: 2.5,
    volume: 122.5,
    color: '#DC143C',
    emoji: '🍬',
    shelfLife: '12 meses',
    walmartUrl: 'https://www.walmart.com/ip/twizzlers-strawberry-twists-16-oz/10315375',
    description: 'Twizzlers sabor fresa, 16 oz.',
    packagingType: 'bag',
  },

  // ═══════════ MAS CHOCOLATES Y DULCES ═══════════
  {
    id: 'gv-cocoa-powder-8oz',
    name: 'Great Value Unsweetened Cocoa Powder, 8 oz',
    nameEs: 'Cacao en Polvo Sin Azúcar 8 oz',
    category: 'Chocolates y Dulces',
    weight: 0.5,
    price: 2.48,
    width: 4,
    height: 5.5,
    depth: 2,
    volume: 44,
    color: '#3E2723',
    emoji: '🍫',
    shelfLife: '18 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-unsweetened-cocoa-powder-8-oz/10450606',
    description: 'Cacao en polvo sin azúcar Great Value, 8 oz.',
    packagingType: 'bag',
  },
  {
    id: 'gv-chocolate-candy-10oz',
    name: 'Great Value Chocolate flavored Candy, 10.5 oz',
    nameEs: 'Dulces de Chocolate 10.5 oz',
    category: 'Chocolates y Dulces',
    weight: 0.66,
    price: 3.28,
    width: 7,
    height: 7,
    depth: 2.5,
    volume: 122.5,
    color: '#795548',
    emoji: '🍬',
    shelfLife: '9 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-chocolate-candy-10-5-oz/456294571',
    description: 'Dulces de chocolate Great Value, 10.5 oz.',
    packagingType: 'bag',
  },
  {
    id: 'gv-caramel-11oz',
    name: 'Great Value Soft Caramels, 11 oz',
    nameEs: 'Caramelos Suaves 11 oz',
    category: 'Chocolates y Dulces',
    weight: 0.69,
    price: 2.48,
    width: 5,
    height: 6,
    depth: 2,
    volume: 60,
    color: '#C68E17',
    emoji: '🍬',
    shelfLife: '9 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-soft-caramels-11-oz/456294575',
    description: 'Caramelos suaves Great Value, 11 oz.',
    packagingType: 'bag',
  },
  {
    id: 'gv-gummy-bears-4oz',
    name: 'Great Value Gummy Bears, 4 oz',
    nameEs: 'Ositos de Gomita 4 oz',
    category: 'Chocolates y Dulces',
    weight: 0.25,
    price: 1.28,
    width: 4,
    height: 5,
    depth: 1.5,
    volume: 30,
    color: '#E91E63',
    emoji: '🐻',
    shelfLife: '9 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-gummy-bears-4-oz/456294577',
    description: 'Ositos de gomita Great Value, 4 oz.',
    packagingType: 'bag',
  },

  // ═══════════ MAS GRANOS NO PERECEDEROS ═══════════
  {
    id: 'gv-wheat-flour-5lb',
    name: 'Great Value Whole Wheat Flour, 5 lb',
    nameEs: 'Harina de Trigo Integral 5 lb',
    category: 'Granos y Cereales',
    weight: 5,
    price: 3.98,
    width: 7.5,
    height: 10,
    depth: 2.5,
    volume: 187.5,
    color: '#D2B48C',
    emoji: '🌾',
    shelfLife: '12 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-whole-wheat-flour-5-lb/10450641',
    description: 'Harina de trigo integral Great Value, 5 libras.',
    packagingType: 'bag',
  },
  {
    id: 'gv-jasmine-rice-5lb',
    name: 'Great Value Jasmine Rice, 5 lb',
    nameEs: 'Arroz Jasmin 5 lb',
    category: 'Granos y Cereales',
    weight: 5,
    price: 4.28,
    width: 7.5,
    height: 10,
    depth: 2.5,
    volume: 187.5,
    color: '#F5F5DC',
    emoji: '🍚',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-jasmine-rice-5-lb/456294585',
    description: 'Arroz jasmin Great Value, 5 libras.',
    packagingType: 'bag',
  },
  {
    id: 'gv-red-beans-2lb',
    name: 'Great Value Dried Red Beans, 2 lb',
    nameEs: 'Frijoles Rojos Secos 2 lb',
    category: 'Granos y Cereales',
    weight: 2,
    price: 2.62,
    width: 7,
    height: 9,
    depth: 2.5,
    volume: 157.5,
    color: '#8B0000',
    emoji: '🫘',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-dried-red-beans-2-lb/456294587',
    description: 'Frijoles rojos secos Great Value, 2 libras.',
    packagingType: 'bag',
  },
  {
    id: 'gv-white-beans-2lb',
    name: 'Great Value Dried White Beans, 2 lb',
    nameEs: 'Frijoles Blancos Secos 2 lb',
    category: 'Granos y Cereales',
    weight: 2,
    price: 2.62,
    width: 7,
    height: 9,
    depth: 2.5,
    volume: 157.5,
    color: '#FAEBD7',
    emoji: '🫘',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-dried-navy-beans-2-lb/456294589',
    description: 'Frijoles blancos secos Great Value, 2 libras.',
    packagingType: 'bag',
  },
  {
    id: 'gv-split-peas-16oz',
    name: 'Great Value Split Peas, 16 oz',
    nameEs: 'Arvejas Partidas 16 oz',
    category: 'Granos y Cereales',
    weight: 1,
    price: 1.48,
    width: 5,
    height: 7,
    depth: 2,
    volume: 70,
    color: '#90EE90',
    emoji: '🫘',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-split-peas-16-oz/456294591',
    description: 'Arvejas partidas secas Great Value, 16 oz.',
    packagingType: 'bag',
  },
  {
    id: 'gv-barley-16oz',
    name: 'Great Value Pearl Barley, 16 oz',
    nameEs: 'Cebada Perlada 16 oz',
    category: 'Granos y Cereales',
    weight: 1,
    price: 1.78,
    width: 5,
    height: 7,
    depth: 2,
    volume: 70,
    color: '#DEB887',
    emoji: '🌾',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-pearl-barley-16-oz/456294593',
    description: 'Cebada perlada Great Value, 16 oz.',
    packagingType: 'bag',
  },
  {
    id: 'gv-rotini-16oz',
    name: 'Great Value Rotini Pasta, 16 oz',
    nameEs: 'Rotini Pasta 16 oz',
    category: 'Granos y Cereales',
    weight: 1,
    price: 1.18,
    width: 3,
    height: 8,
    depth: 2.5,
    volume: 60,
    color: '#FFDEAD',
    emoji: '🍝',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-rotini-pasta-16-oz/10450635',
    description: 'Rotini pasta Great Value, 16 oz.',
    packagingType: 'box',
  },
  {
    id: 'gv-fettuccine-16oz',
    name: 'Great Value Fettuccine Pasta, 16 oz',
    nameEs: 'Fettuccine 16 oz',
    category: 'Granos y Cereales',
    weight: 1,
    price: 1.18,
    width: 3,
    height: 8,
    depth: 2.5,
    volume: 60,
    color: '#FFE4B5',
    emoji: '🍝',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-fettuccine-16-oz/10450637',
    description: 'Fettuccine Great Value, 16 oz.',
    packagingType: 'box',
  },
  {
    id: 'gv-egg-noodles-12oz',
    name: 'Great Value Egg Noodles, 12 oz',
    nameEs: 'Fideos de Huevo 12 oz',
    category: 'Granos y Cereales',
    weight: 0.75,
    price: 1.48,
    width: 3,
    height: 8,
    depth: 2,
    volume: 48,
    color: '#FFD700',
    emoji: '🍝',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-egg-noodles-12-oz/456294595',
    description: 'Fideos de huevo Great Value, 12 oz.',
    packagingType: 'bag',
  },
  {
    id: 'gv-lasagna-16oz',
    name: 'Great Value Lasagna Pasta, 16 oz',
    nameEs: 'Lasagna Pasta 16 oz',
    category: 'Granos y Cereales',
    weight: 1,
    price: 1.48,
    width: 3,
    height: 8,
    depth: 2.5,
    volume: 60,
    color: '#FFDEAD',
    emoji: '🍝',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-lasagna-16-oz/10450639',
    description: 'Lasagna pasta Great Value, 16 oz.',
    packagingType: 'box',
  },
  {
    id: 'gv-shell-pasta-16oz',
    name: 'Great Value Medium Shell Pasta, 16 oz',
    nameEs: 'Conchitas Pasta 16 oz',
    category: 'Granos y Cereales',
    weight: 1,
    price: 1.18,
    width: 3,
    height: 8,
    depth: 2.5,
    volume: 60,
    color: '#FFE4B5',
    emoji: '🍝',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-medium-shell-pasta-16-oz/10450633',
    description: 'Conchitas pasta Great Value, 16 oz.',
    packagingType: 'box',
  },

  // ═══════════ MAS SEMILLAS Y FRUTOS SECOS ═══════════
  {
    id: 'gv-walnuts-8oz',
    name: 'Great Value Chopped Walnuts, 8 oz',
    nameEs: 'Nueces Picadas 8 oz',
    category: 'Semillas y Frutos Secos',
    weight: 0.5,
    price: 4.48,
    width: 4,
    height: 6,
    depth: 2,
    volume: 48,
    color: '#8B6914',
    emoji: '🌰',
    shelfLife: '12 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-chopped-walnuts-8-oz/456294597',
    description: 'Nueces picadas Great Value, 8 oz.',
    packagingType: 'bag',
  },
  {
    id: 'gv-pecans-5oz',
    name: 'Great Value Pecan Halves, 5 oz',
    nameEs: 'Nueces Pecan Mitades 5 oz',
    category: 'Semillas y Frutos Secos',
    weight: 0.31,
    price: 5.48,
    width: 3.5,
    height: 5.5,
    depth: 2,
    volume: 38.5,
    color: '#A0522D',
    emoji: '🌰',
    shelfLife: '12 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-pecan-halves-5-oz/456294599',
    description: 'Nueces pecan mitades Great Value, 5 oz.',
    packagingType: 'bag',
  },
  {
    id: 'gv-cashews-8oz',
    name: 'Great Value Roasted Cashews, 8.5 oz',
    nameEs: 'Anacardos Tostados 8.5 oz',
    category: 'Semillas y Frutos Secos',
    weight: 0.53,
    price: 5.98,
    width: 4,
    height: 6,
    depth: 2.5,
    volume: 60,
    color: '#DEB887',
    emoji: '🥜',
    shelfLife: '12 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-roasted-cashews-8-5-oz/456294601',
    description: 'Anacardos tostados Great Value, 8.5 oz.',
    packagingType: 'bag',
  },
  {
    id: 'gv-cranberries-6oz',
    name: 'Great Value Dried Cranberries, 6 oz',
    nameEs: 'Arandanos Secos 6 oz',
    category: 'Semillas y Frutos Secos',
    weight: 0.38,
    price: 3.28,
    width: 4,
    height: 6,
    depth: 2,
    volume: 48,
    color: '#DC143C',
    emoji: '🫐',
    shelfLife: '12 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-dried-cranberries-6-oz/456294603',
    description: 'Arandanos rojos secos Great Value, 6 oz.',
    packagingType: 'bag',
  },

  // ═══════════ MAS LACTEOS ESTABLES ═══════════
  {
    id: 'lc-condensed-14oz-2pk',
    name: 'Nestle La Lechera Sweetened Condensed Milk, 14 oz, 2 Pack',
    nameEs: 'Leche Condensada La Lechera ×2',
    category: 'Lácteos Estables',
    weight: 1.75,
    price: 4.28,
    width: 5,
    height: 4.5,
    depth: 3,
    volume: 67.5,
    color: '#FFF8DC',
    emoji: '🥛',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/nestle-la-lechera-sweetened-condensed-milk-14-oz-2-count/10312655',
    description: 'Pack de 2 latas de leche condensada La Lechera, 14 oz c/u.',
    packagingType: 'can',
  },
  {
    id: 'gv-condensed-14oz-2pk',
    name: 'Great Value Sweetened Condensed Milk, 14 oz, 2 Pack',
    nameEs: 'Leche Condensada GV ×2',
    category: 'Lácteos Estables',
    weight: 1.75,
    price: 3.98,
    width: 5,
    height: 4.5,
    depth: 3,
    volume: 67.5,
    color: '#F5DEB3',
    emoji: '🥛',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-sweetened-condensed-milk-14-oz-2-count/456294605',
    description: 'Pack de 2 latas de leche condensada Great Value.',
    packagingType: 'can',
  },

  // ═══════════ PEQUENOS PARA RELLENAR ═══════════
  {
    id: 'gv-bouillon-36ct',
    name: 'Great Value Beef Bouillon Cubes, 36 ct',
    nameEs: 'Cubos de Caldo de Res ×36',
    category: 'Condimentos y Salsas',
    weight: 0.56,
    price: 1.98,
    width: 5,
    height: 3.5,
    depth: 1.5,
    volume: 26.25,
    color: '#8B4513',
    emoji: '🧊',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-beef-bouillon-cubes-36-count/10450645',
    description: 'Cubos de caldo de res Great Value, 36 unidades.',
    packagingType: 'box',
  },
  {
    id: 'knorr-chicken-bouillon',
    name: 'Knorr Chicken Bouillon, 8 ct',
    nameEs: 'Cubos de Caldo de Pollo Knorr ×8',
    category: 'Condimentos y Salsas',
    weight: 0.22,
    price: 1.98,
    width: 3,
    height: 4,
    depth: 1.5,
    volume: 18,
    color: '#DAA520',
    emoji: '🧊',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/knorr-chicken-bouillon-8-count/10314280',
    description: 'Cubos de caldo de pollo Knorr, 8 unidades.',
    packagingType: 'box',
  },
  {
    id: 'gv-gelatin-6oz-4pk',
    name: 'Great Value Gelatin, 6 oz, 4 Pack',
    nameEs: 'Gelatina ×4 sobres',
    category: 'Snacks y Desayuno',
    weight: 0.5,
    price: 2.48,
    width: 7,
    height: 4,
    depth: 2,
    volume: 56,
    color: '#FF69B4',
    emoji: '🍮',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-gelatin-6-oz-4-count/456294607',
    description: 'Gelatina Great Value, 4 sobres de 6 oz.',
    packagingType: 'box',
  },
  {
    id: 'gv-instant-pudding-4pk',
    name: 'Great Value Instant Pudding, 5.1 oz, 4 Pack',
    nameEs: 'Pudding Instantaneo ×4 sobres',
    category: 'Snacks y Desayuno',
    weight: 0.5,
    price: 2.48,
    width: 7,
    height: 4,
    depth: 2,
    volume: 56,
    color: '#FFD700',
    emoji: '🍮',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-instant-pudding-5-1-oz-4-count/456294609',
    description: 'Pudding instantaneo Great Value, 4 sobres.',
    packagingType: 'box',
  },
  {
    id: 'gv-chicken-noodle-soup-4pk',
    name: 'Great Value Chicken Noodle Soup, 10.5 oz, 4 Pack',
    nameEs: 'Sopa de Pollo con Fideos ×4 latas',
    category: 'Enlatados',
    weight: 2.6,
    price: 2.98,
    width: 7,
    height: 4,
    depth: 3,
    volume: 84,
    color: '#FFD700',
    emoji: '🍲',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-chicken-noodle-soup-10-5-oz-4-count/456294611',
    description: 'Sopa de pollo con fideos Great Value, 4 latas.',
    packagingType: 'can',
  },
  {
    id: 'gv-tomato-soup-4pk',
    name: 'Great Value Tomato Soup, 10.75 oz, 4 Pack',
    nameEs: 'Sopa de Tomate ×4 latas',
    category: 'Enlatados',
    weight: 2.7,
    price: 2.98,
    width: 7,
    height: 4,
    depth: 3,
    volume: 84,
    color: '#DC143C',
    emoji: '🍅',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-tomato-soup-10-75-oz-4-count/456294613',
    description: 'Sopa de tomate Great Value, 4 latas.',
    packagingType: 'can',
  },
  {
    id: 'gv-baking-powder-8oz',
    name: 'Great Value Baking Powder, 8.1 oz',
    nameEs: 'Polvo para Hornear 8.1 oz',
    category: 'Granos y Cereales',
    weight: 0.51,
    price: 1.68,
    width: 3,
    height: 5,
    depth: 2,
    volume: 30,
    color: '#FF8C00',
    emoji: '🧁',
    shelfLife: '18 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-baking-powder-8-1-oz/456294615',
    description: 'Polvo para hornear Great Value, 8.1 oz.',
    packagingType: 'can',
  },
  {
    id: 'gv-baking-soda-16oz',
    name: 'Great Value Baking Soda, 16 oz',
    nameEs: 'Bicarbonato de Sosa 16 oz',
    category: 'Granos y Cereales',
    weight: 1,
    price: 0.88,
    width: 3.5,
    height: 5.5,
    depth: 2,
    volume: 38.5,
    color: '#FF8C00',
    emoji: '🧁',
    shelfLife: '36 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-baking-soda-16-oz/456294617',
    description: 'Bicarbonato de sodio Great Value, 16 oz.',
    packagingType: 'box',
  },
  {
    id: 'gv-vanilla-2oz',
    name: 'Great Value Pure Vanilla Extract, 2 oz',
    nameEs: 'Extracto de Vainilla Pura 2 oz',
    category: 'Condimentos y Salsas',
    weight: 0.13,
    price: 3.28,
    width: 1.5,
    height: 4.5,
    depth: 1.5,
    volume: 10.13,
    color: '#8B4513',
    emoji: '🫗',
    shelfLife: '36 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-pure-vanilla-extract-2-oz/456294619',
    description: 'Extracto de vainilla pura Great Value, 2 oz.',
    packagingType: 'bottle',
  },
  {
    id: 'gv-chili-powder-2oz',
    name: 'Great Value Chili Powder, 2.25 oz',
    nameEs: 'Chile en Polvo 2.25 oz',
    category: 'Condimentos y Salsas',
    weight: 0.14,
    price: 1.48,
    width: 2.5,
    height: 4.5,
    depth: 1.5,
    volume: 16.88,
    color: '#8B0000',
    emoji: '🌶️',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-chili-powder-2-25-oz/456294621',
    description: 'Chile en polvo Great Value, 2.25 oz.',
    packagingType: 'box',
  },
  {
    id: 'gv-paprika-2oz',
    name: 'Great Value Paprika, 2.5 oz',
    nameEs: 'Pimenton Dulce 2.5 oz',
    category: 'Condimentos y Salsas',
    weight: 0.16,
    price: 1.28,
    width: 2.5,
    height: 4.5,
    depth: 1.5,
    volume: 16.88,
    color: '#DC143C',
    emoji: '🌶️',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-paprika-2-5-oz/456294623',
    description: 'Pimenton dulce Great Value, 2.5 oz.',
    packagingType: 'box',
  },
  {
    id: 'gv-cinnamon-3oz',
    name: 'Great Value Ground Cinnamon, 3 oz',
    nameEs: 'Canela Molida 3 oz',
    category: 'Condimentos y Salsas',
    weight: 0.19,
    price: 1.98,
    width: 2.5,
    height: 5,
    depth: 1.5,
    volume: 18.75,
    color: '#8B4513',
    emoji: '🫙',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-ground-cinnamon-3-oz/456294625',
    description: 'Canela molida Great Value, 3 oz.',
    packagingType: 'box',
  },
  {
    id: 'gv-chili-beans-3pk',
    name: 'Great Value Chili Beans in Mild Sauce, 15.5 oz, 3 Pack',
    nameEs: 'Frijoles para Chili ×3 latas',
    category: 'Enlatados',
    weight: 2.9,
    price: 2.78,
    width: 7,
    height: 5,
    depth: 3.5,
    volume: 122.5,
    color: '#B22222',
    emoji: '🥫',
    shelfLife: '36 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-chili-beans-in-mild-sauce-15-5-oz-3-count/456294627',
    description: 'Frijoles para chili Great Value, 3 latas de 15.5 oz.',
    packagingType: 'can',
  },
  {
    id: 'gv-pinto-beans-15oz-3pk',
    name: 'Great Value Pinto Beans in Sauce, 15.5 oz, 3 Pack',
    nameEs: 'Frijoles Pintos en Salsa ×3',
    category: 'Enlatados',
    weight: 2.9,
    price: 2.78,
    width: 7,
    height: 5,
    depth: 3.5,
    volume: 122.5,
    color: '#A0522D',
    emoji: '🥫',
    shelfLife: '36 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-pinto-beans-in-sauce-15-5-oz-3-count/456294629',
    description: 'Frijoles pintos en salsa Great Value, 3 latas.',
    packagingType: 'can',
  },
  {
    id: 'gv-mushrooms-3pk',
    name: 'Great Value Sliced Mushrooms, 4 oz, 3 Pack',
    nameEs: 'Hongos Rebanados ×3 latas',
    category: 'Enlatados',
    weight: 0.75,
    price: 1.98,
    width: 5,
    height: 3.5,
    depth: 3,
    volume: 52.5,
    color: '#DEB887',
    emoji: '🍄',
    shelfLife: '36 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-sliced-mushrooms-4-oz-3-count/456294631',
    description: 'Hongos rebanados enlatados Great Value, 3 latas.',
    packagingType: 'can',
  },

  // ═══════════ MAS ASEO PERSONAL ═══════════
  {
    id: 'gv-body-lotion-16oz',
    name: 'Great Value Body Lotion, Original, 16 oz',
    nameEs: 'Loción Corporal 16 oz',
    category: 'Aseo Personal',
    weight: 1,
    price: 3.28,
    width: 3,
    height: 7,
    depth: 3,
    volume: 63,
    color: '#E8D5F5',
    emoji: '🧴',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-daily-body-lotion-original-16-oz/456294580',
    description: 'Loción corporal diaria Great Value, 16 oz.',
    packagingType: 'bottle',
  },
  {
    id: 'gv-conditioner-12oz',
    name: 'Suave Professionals Conditioner, 12 oz',
    nameEs: 'Acondicionador Suave 12 oz',
    category: 'Aseo Personal',
    weight: 0.75,
    price: 3.48,
    width: 2.5,
    height: 7.5,
    depth: 2.5,
    volume: 46.88,
    color: '#BA68C8',
    emoji: '🧴',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/suave-professionals-keratin-infusion-conditioner-12-oz/456154216',
    description: 'Acondicionador profesional Suave, 12 oz.',
    packagingType: 'bottle',
  },
  {
    id: 'gv-hand-soap-7oz',
    name: 'Dial Complete Hand Soap, 7.5 oz',
    nameEs: 'Jabón de Manos 7.5 oz',
    category: 'Aseo Personal',
    weight: 0.47,
    price: 2.48,
    width: 2.5,
    height: 6.5,
    depth: 2.5,
    volume: 40.63,
    color: '#90CAF9',
    emoji: '🧼',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/dial-complete-antibacterial-hand-soap-7-5-oz/10313826',
    description: 'Jabón de manos antibacterial Dial, 7.5 oz.',
    packagingType: 'bottle',
  },
  {
    id: 'gv-shampoo-2pk',
    name: 'Great Value Shampoo, 2 Pack',
    nameEs: 'Champú Great Value ×2',
    category: 'Aseo Personal',
    weight: 1.5,
    price: 4.48,
    width: 5,
    height: 7.5,
    depth: 2.5,
    volume: 93.75,
    color: '#9370DB',
    emoji: '🧴',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-shampoo-2-count/456294582',
    description: 'Pack de 2 champús Great Value.',
    packagingType: 'bottle',
  },

  // ═══════════ MAS ASEO DEL HOGAR ═══════════
  {
    id: 'gv-fabuloso-56oz',
    name: 'Fabuloso All Purpose Cleaner, Lavender, 56 oz',
    nameEs: 'Limpiador Multiusos Fabuloso 56 oz',
    category: 'Aseo del Hogar',
    weight: 3.5,
    price: 3.98,
    width: 4,
    height: 10.5,
    depth: 3.5,
    volume: 147,
    color: '#7E57C2',
    emoji: '🧹',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/fabuloso-multi-purpose-cleaner-lavender-56-oz/10313827',
    description: 'Limpiador multiusos Fabuloso lavanda, 56 oz.',
    packagingType: 'bottle',
  },
  {
    id: 'gv-baking-soda-2lb',
    name: 'Arm & Hammer Baking Soda, 2 lb',
    nameEs: 'Bicarbonato de Sodio 2 lb',
    category: 'Aseo del Hogar',
    weight: 2,
    price: 1.48,
    width: 4,
    height: 5,
    depth: 3,
    volume: 60,
    color: '#FF8A65',
    emoji: '🧹',
    shelfLife: '36 meses',
    walmartUrl: 'https://www.walmart.com/ip/arm-hammer-baking-sodium-2-lb/10313828',
    description: 'Bicarbonato de sodio Arm & Hammer, 2 libras.',
    packagingType: 'box',
  },
  {
    id: 'gv-aluminum-foil',
    name: 'Great Value Aluminum Foil, 75 sq ft',
    nameEs: 'Papel Aluminio 75 pies²',
    category: 'Aseo del Hogar',
    weight: 0.5,
    price: 3.48,
    width: 10,
    height: 3,
    depth: 3,
    volume: 90,
    color: '#B0BEC5',
    emoji: '🧹',
    shelfLife: '60 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-aluminum-foil-75-sq-ft/10450650',
    description: 'Papel aluminio Great Value, 75 pies cuadrados.',
    packagingType: 'box',
  },
  {
    id: 'gv-tissues-3pk',
    name: 'Great Value Facial Tissues, 3 Pack',
    nameEs: 'Pañuelos Faciales ×3',
    category: 'Aseo del Hogar',
    weight: 0.75,
    price: 2.48,
    width: 8,
    height: 4.5,
    depth: 5,
    volume: 180,
    color: '#E0E0E0',
    emoji: '🧻',
    shelfLife: '24 meses',
    walmartUrl: 'https://www.walmart.com/ip/great-value-facial-tissue-3-count/456294584',
    description: 'Pack de 3 cajas de pañuelos faciales Great Value.',
    packagingType: 'box',
  },
];
